/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) fdrift_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s1[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s2[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

/* fdrift:(i0,i1[13],i2[6])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119, a12, a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=1.7839223988857496e+05;
  a1=5.0000000000000000e-01;
  a2=arg[1]? arg[1][4] : 0;
  a3=(a1*a2);
  a4=arg[1]? arg[1][1] : 0;
  a5=arg[1]? arg[1][0] : 0;
  a6=casadi_sq(a5);
  a7=casadi_sq(a4);
  a6=(a6+a7);
  a7=arg[1]? arg[1][2] : 0;
  a8=casadi_sq(a7);
  a6=(a6+a8);
  a8=arg[1]? arg[1][3] : 0;
  a9=casadi_sq(a8);
  a6=(a6+a9);
  a6=sqrt(a6);
  a4=(a4/a6);
  a3=(a3*a4);
  a9=arg[1]? arg[1][5] : 0;
  a10=(a1*a9);
  a7=(a7/a6);
  a10=(a10*a7);
  a3=(a3+a10);
  a10=arg[1]? arg[1][6] : 0;
  a11=(a1*a10);
  a8=(a8/a6);
  a11=(a11*a8);
  a3=(a3+a11);
  a3=(a0*a3);
  a3=(-a3);
  if (res[0]!=0) res[0][0]=a3;
  a3=(a1*a2);
  a5=(a5/a6);
  a3=(a3*a5);
  a6=(a1*a10);
  a6=(a6*a7);
  a3=(a3+a6);
  a6=(a1*a9);
  a6=(a6*a8);
  a3=(a3-a6);
  a3=(a0*a3);
  if (res[0]!=0) res[0][1]=a3;
  a3=(a1*a9);
  a3=(a3*a5);
  a6=(a1*a10);
  a6=(a6*a4);
  a3=(a3-a6);
  a6=(a1*a2);
  a6=(a6*a8);
  a3=(a3+a6);
  a3=(a0*a3);
  if (res[0]!=0) res[0][2]=a3;
  a3=(a1*a10);
  a3=(a3*a5);
  a6=(a1*a9);
  a6=(a6*a4);
  a3=(a3+a6);
  a6=(a1*a2);
  a6=(a6*a7);
  a3=(a3-a6);
  a3=(a0*a3);
  if (res[0]!=0) res[0][3]=a3;
  a3=8.3333333333333326e+02;
  a6=(a3*a9);
  a11=(a10*a6);
  a12=1.6666666666666665e+03;
  a13=(a12*a10);
  a14=(a9*a13);
  a11=(a11-a14);
  a11=(a11/a3);
  a11=(a0*a11);
  if (res[0]!=0) res[0][4]=a11;
  a13=(a2*a13);
  a11=(a3*a2);
  a10=(a10*a11);
  a13=(a13-a10);
  a13=(a13/a3);
  a13=(a0*a13);
  if (res[0]!=0) res[0][5]=a13;
  a9=(a9*a11);
  a2=(a2*a6);
  a9=(a9-a2);
  a9=(a9/a12);
  a9=(a0*a9);
  if (res[0]!=0) res[0][6]=a9;
  a9=arg[1]? arg[1][10] : 0;
  a12=(a0*a9);
  if (res[0]!=0) res[0][7]=a12;
  a12=arg[1]? arg[1][11] : 0;
  a2=(a0*a12);
  if (res[0]!=0) res[0][8]=a2;
  a2=arg[1]? arg[1][12] : 0;
  a6=(a0*a2);
  if (res[0]!=0) res[0][9]=a6;
  a6=arg[2]? arg[2][0] : 0;
  a11=casadi_sq(a6);
  a13=arg[2]? arg[2][1] : 0;
  a3=casadi_sq(a13);
  a11=(a11+a3);
  a3=arg[2]? arg[2][2] : 0;
  a10=casadi_sq(a3);
  a11=(a11+a10);
  a11=sqrt(a11);
  a10=(a6/a11);
  a14=1000.;
  a15=-6.4000000000000001e-01;
  a16=2.5000000000000000e-01;
  a17=2500.;
  a18=2.;
  a19=(a4*a8);
  a20=(a5*a7);
  a19=(a19+a20);
  a19=(a18*a19);
  a19=(a17*a19);
  a20=arg[2]? arg[2][3] : 0;
  a21=arg[2]? arg[2][4] : 0;
  a22=(a6*a21);
  a23=(a13*a20);
  a22=(a22-a23);
  a23=arg[2]? arg[2][5] : 0;
  a24=(a13*a23);
  a25=(a3*a21);
  a24=(a24-a25);
  a25=casadi_sq(a24);
  a26=(a3*a20);
  a27=(a6*a23);
  a26=(a26-a27);
  a27=casadi_sq(a26);
  a25=(a25+a27);
  a27=casadi_sq(a22);
  a25=(a25+a27);
  a25=sqrt(a25);
  a22=(a22/a25);
  a27=(a22*a10);
  a24=(a24/a25);
  a28=(a3/a11);
  a29=(a24*a28);
  a27=(a27-a29);
  a26=(a26/a25);
  a25=(a26*a28);
  a11=(a13/a11);
  a29=(a22*a11);
  a25=(a25-a29);
  a29=casadi_sq(a25);
  a30=casadi_sq(a27);
  a29=(a29+a30);
  a30=(a24*a11);
  a31=(a26*a10);
  a30=(a30-a31);
  a31=casadi_sq(a30);
  a29=(a29+a31);
  a29=sqrt(a29);
  a27=(a27/a29);
  a31=(a27*a22);
  a30=(a30/a29);
  a32=(a30*a26);
  a31=(a31-a32);
  a32=(a27*a22);
  a33=(a30*a26);
  a32=(a32-a33);
  a32=(a10*a32);
  a25=(a25/a29);
  a29=(a25*a22);
  a33=(a30*a24);
  a29=(a29-a33);
  a29=(a11*a29);
  a32=(a32-a29);
  a29=(a25*a26);
  a33=(a27*a24);
  a29=(a29-a33);
  a29=(a28*a29);
  a32=(a32+a29);
  a31=(a31/a32);
  a29=(a13*a23);
  a33=(a3*a21);
  a29=(a29-a33);
  a33=casadi_sq(a6);
  a34=casadi_sq(a13);
  a33=(a33+a34);
  a34=casadi_sq(a3);
  a33=(a33+a34);
  a34=(a29/a33);
  a35=-1.9094623163594840e+09;
  a36=1.7453292519943295e-02;
  a37=1.7487317400000001e+02;
  a38=-2.4109079999999999e-01;
  a39=2.4562962500000000e+06;
  a40=arg[0]? arg[0][0] : 0;
  a40=(a0*a40);
  a41=86400.;
  a42=(a40/a41);
  a42=(a39+a42);
  a43=2451545.;
  a42=(a42-a43);
  a44=36525.;
  a42=(a42/a44);
  a45=(a38*a42);
  a45=(a37+a45);
  a46=4.0670000000000002e-05;
  a47=casadi_sq(a42);
  a48=(a46*a47);
  a45=(a45+a48);
  a48=-1.3270000000000000e-06;
  a49=casadi_sq(a42);
  a49=(a49*a42);
  a50=(a48*a49);
  a45=(a45+a50);
  a45=(a36*a45);
  a50=(-a45);
  a50=cos(a50);
  a51=1.0293734800000000e+02;
  a52=3.2255570000000000e-01;
  a53=(a52*a42);
  a53=(a51+a53);
  a54=1.5025999999999999e-04;
  a55=(a54*a47);
  a53=(a53+a55);
  a55=4.7800000000000002e-07;
  a56=(a55*a49);
  a53=(a53+a56);
  a53=(a36*a53);
  a56=(a53-a45);
  a57=(-a56);
  a57=cos(a57);
  a58=(a50*a57);
  a59=(-a45);
  a59=sin(a59);
  a60=1.3054600000000000e-02;
  a61=(a60*a42);
  a62=-9.3100000000000006e-06;
  a63=(a62*a47);
  a61=(a61+a63);
  a63=-3.4000000000000000e-08;
  a64=(a63*a49);
  a61=(a61+a64);
  a61=(a36*a61);
  a64=(-a61);
  a64=cos(a64);
  a59=(a59*a64);
  a65=(-a56);
  a65=sin(a65);
  a66=(a59*a65);
  a58=(a58-a66);
  a66=1.4959802299063239e+08;
  a67=1.;
  a68=1.6708620000000000e-02;
  a69=-4.2036999999999997e-05;
  a70=(a69*a42);
  a70=(a68+a70);
  a71=-1.2360000000000000e-07;
  a72=(a71*a47);
  a70=(a70+a72);
  a72=3.9999999999999998e-11;
  a49=(a72*a49);
  a70=(a70+a49);
  a49=casadi_sq(a70);
  a49=(a67-a49);
  a49=(a66*a49);
  a73=1.0046644900000000e+02;
  a74=3.5999372851900000e+04;
  a42=(a74*a42);
  a42=(a73+a42);
  a75=-5.6799999999999998e-06;
  a47=(a75*a47);
  a42=(a42+a47);
  a42=(a36*a42);
  a42=(a42-a53);
  a53=(a18*a70);
  a47=casadi_sq(a70);
  a47=(a70*a47);
  a76=4.;
  a47=(a47/a76);
  a53=(a53-a47);
  a47=5.2083333333333336e-02;
  a77=casadi_sq(a70);
  a77=casadi_sq(a77);
  a77=(a70*a77);
  a77=(a47*a77);
  a53=(a53+a77);
  a77=sin(a42);
  a53=(a53*a77);
  a77=1.2500000000000000e+00;
  a78=casadi_sq(a70);
  a78=(a77*a78);
  a79=4.5833333333333331e-01;
  a80=casadi_sq(a70);
  a80=casadi_sq(a80);
  a80=(a79*a80);
  a78=(a78-a80);
  a80=(a18*a42);
  a80=sin(a80);
  a78=(a78*a80);
  a53=(a53+a78);
  a78=1.0833333333333333e+00;
  a80=casadi_sq(a70);
  a80=(a70*a80);
  a80=(a78*a80);
  a81=6.7187500000000000e-01;
  a82=casadi_sq(a70);
  a82=casadi_sq(a82);
  a82=(a70*a82);
  a82=(a81*a82);
  a80=(a80-a82);
  a82=3.;
  a83=(a82*a42);
  a83=sin(a83);
  a80=(a80*a83);
  a53=(a53+a80);
  a80=1.0729166666666667e+00;
  a83=casadi_sq(a70);
  a83=casadi_sq(a83);
  a83=(a80*a83);
  a84=(a76*a42);
  a84=sin(a84);
  a83=(a83*a84);
  a53=(a53+a83);
  a83=1.1427083333333334e+00;
  a84=casadi_sq(a70);
  a84=casadi_sq(a84);
  a84=(a70*a84);
  a84=(a83*a84);
  a85=5.;
  a86=(a85*a42);
  a86=sin(a86);
  a84=(a84*a86);
  a53=(a53+a84);
  a42=(a42+a53);
  a53=cos(a42);
  a53=(a70*a53);
  a53=(a67+a53);
  a49=(a49/a53);
  a53=cos(a42);
  a53=(a49*a53);
  a84=(a58*a53);
  a86=(-a56);
  a86=sin(a86);
  a50=(a50*a86);
  a56=(-a56);
  a56=cos(a56);
  a59=(a59*a56);
  a50=(a50+a59);
  a59=sin(a42);
  a49=(a49*a59);
  a59=(a50*a49);
  a84=(a84+a59);
  a84=(a84+a6);
  a59=(a35*a84);
  a87=casadi_sq(a84);
  a88=9.1748200035787253e-01;
  a89=(-a45);
  a89=cos(a89);
  a89=(a89*a64);
  a64=(a89*a56);
  a45=(-a45);
  a45=sin(a45);
  a86=(a45*a86);
  a64=(a64-a86);
  a86=(a64*a49);
  a45=(a45*a57);
  a89=(a89*a65);
  a45=(a45+a89);
  a89=(a45*a53);
  a86=(a86-a89);
  a89=(a88*a86);
  a57=-3.9777729827042280e-01;
  a61=(-a61);
  a61=sin(a61);
  a65=(a61*a65);
  a53=(a65*a53);
  a61=(a61*a56);
  a49=(a61*a49);
  a53=(a53-a49);
  a49=(a57*a53);
  a89=(a89+a49);
  a89=(a89+a13);
  a49=casadi_sq(a89);
  a87=(a87+a49);
  a49=3.9777729827042280e-01;
  a86=(a49*a86);
  a53=(a88*a53);
  a86=(a86+a53);
  a86=(a86+a3);
  a53=casadi_sq(a86);
  a87=(a87+a53);
  a53=sqrt(a87);
  a53=(a53*a87);
  a59=(a59/a53);
  a87=casadi_sq(a29);
  a56=(a3*a20);
  a90=(a6*a23);
  a56=(a56-a90);
  a90=casadi_sq(a56);
  a87=(a87+a90);
  a90=(a6*a21);
  a91=(a13*a20);
  a90=(a90-a91);
  a91=casadi_sq(a90);
  a87=(a87+a91);
  a91=sqrt(a87);
  a92=(a29/a91);
  a93=(a59*a92);
  a94=(a35*a89);
  a94=(a94/a53);
  a95=(a56/a91);
  a96=(a94*a95);
  a93=(a93+a96);
  a35=(a35*a86);
  a35=(a35/a53);
  a53=(a90/a91);
  a96=(a35*a53);
  a93=(a93+a96);
  a96=(a93*a6);
  a96=(a96/a91);
  a34=(a34-a96);
  a96=(a25*a34);
  a97=(a56/a33);
  a98=(a93*a13);
  a98=(a98/a91);
  a97=(a97-a98);
  a98=(a27*a97);
  a96=(a96+a98);
  a98=(a90/a33);
  a93=(a93*a3);
  a93=(a93/a91);
  a98=(a98-a93);
  a93=(a30*a98);
  a96=(a96+a93);
  a93=arg[1]? arg[1][9] : 0;
  a99=(a96*a93);
  a100=(a24*a34);
  a101=(a26*a97);
  a100=(a100+a101);
  a101=(a22*a98);
  a100=(a100+a101);
  a101=arg[1]? arg[1][8] : 0;
  a102=(a100*a101);
  a99=(a99-a102);
  a99=(a9+a99);
  a31=(a31*a99);
  a102=(a11*a22);
  a103=(a28*a26);
  a102=(a102-a103);
  a102=(a102/a32);
  a103=arg[1]? arg[1][7] : 0;
  a104=(a100*a103);
  a34=(a10*a34);
  a97=(a11*a97);
  a34=(a34+a97);
  a98=(a28*a98);
  a34=(a34+a98);
  a98=(a34*a93);
  a104=(a104-a98);
  a104=(a12+a104);
  a102=(a102*a104);
  a31=(a31-a102);
  a102=(a11*a30);
  a98=(a28*a27);
  a102=(a102-a98);
  a102=(a102/a32);
  a98=(a34*a101);
  a97=(a96*a103);
  a98=(a98-a97);
  a98=(a2+a98);
  a102=(a102*a98);
  a31=(a31+a102);
  a31=(a20+a31);
  a102=7.2921240000000005e-05;
  a97=(a10*a22);
  a105=(a28*a24);
  a97=(a97-a105);
  a105=(a27*a22);
  a106=(a30*a26);
  a105=(a105-a106);
  a105=(a10*a105);
  a106=(a25*a22);
  a107=(a30*a24);
  a106=(a106-a107);
  a106=(a11*a106);
  a105=(a105-a106);
  a106=(a25*a26);
  a107=(a27*a24);
  a106=(a106-a107);
  a106=(a28*a106);
  a105=(a105+a106);
  a97=(a97/a105);
  a97=(a97*a101);
  a106=(a25*a22);
  a107=(a30*a24);
  a106=(a106-a107);
  a106=(a106/a105);
  a107=sqrt(a33);
  a107=(a107+a103);
  a106=(a106*a107);
  a97=(a97-a106);
  a106=(a10*a30);
  a108=(a28*a25);
  a106=(a106-a108);
  a106=(a106/a105);
  a106=(a106*a93);
  a97=(a97-a106);
  a106=(a102*a97);
  a31=(a31+a106);
  a106=casadi_sq(a31);
  a108=(a10*a22);
  a109=(a28*a24);
  a108=(a108-a109);
  a108=(a108/a32);
  a108=(a108*a104);
  a109=(a25*a22);
  a110=(a30*a24);
  a109=(a109-a110);
  a109=(a109/a32);
  a109=(a109*a99);
  a108=(a108-a109);
  a109=(a10*a30);
  a110=(a28*a25);
  a109=(a109-a110);
  a109=(a109/a32);
  a109=(a109*a98);
  a108=(a108-a109);
  a108=(a21+a108);
  a109=(a27*a22);
  a110=(a30*a26);
  a109=(a109-a110);
  a109=(a109/a105);
  a109=(a109*a107);
  a110=(a11*a22);
  a111=(a28*a26);
  a110=(a110-a111);
  a110=(a110/a105);
  a110=(a110*a101);
  a109=(a109-a110);
  a110=(a11*a30);
  a111=(a28*a27);
  a110=(a110-a111);
  a110=(a110/a105);
  a110=(a110*a93);
  a109=(a109+a110);
  a110=(a102*a109);
  a108=(a108-a110);
  a110=casadi_sq(a108);
  a106=(a106+a110);
  a110=(a25*a26);
  a111=(a27*a24);
  a110=(a110-a111);
  a110=(a110/a32);
  a110=(a110*a99);
  a99=(a10*a26);
  a111=(a11*a24);
  a99=(a99-a111);
  a99=(a99/a32);
  a99=(a99*a104);
  a110=(a110-a99);
  a99=(a10*a27);
  a104=(a11*a25);
  a99=(a99-a104);
  a99=(a99/a32);
  a99=(a99*a98);
  a110=(a110+a99);
  a110=(a23+a110);
  a99=casadi_sq(a110);
  a106=(a106+a99);
  a106=sqrt(a106);
  a99=(a31/a106);
  a19=(a19*a99);
  a98=(a7*a8);
  a32=(a5*a4);
  a98=(a98-a32);
  a98=(a18*a98);
  a98=(a17*a98);
  a32=(a108/a106);
  a98=(a98*a32);
  a19=(a19+a98);
  a98=casadi_sq(a5);
  a104=casadi_sq(a4);
  a98=(a98-a104);
  a104=casadi_sq(a7);
  a98=(a98-a104);
  a104=casadi_sq(a8);
  a98=(a98+a104);
  a17=(a17*a98);
  a106=(a110/a106);
  a17=(a17*a106);
  a19=(a19+a17);
  a19=fabs(a19);
  a16=(a16*a19);
  a15=(a15*a16);
  a16=casadi_sq(a109);
  a19=casadi_sq(a97);
  a16=(a16+a19);
  a19=(a25*a26);
  a17=(a27*a24);
  a19=(a19-a17);
  a19=(a19/a105);
  a19=(a19*a107);
  a17=(a10*a26);
  a98=(a11*a24);
  a17=(a17-a98);
  a17=(a17/a105);
  a17=(a17*a101);
  a19=(a19-a17);
  a17=(a10*a27);
  a98=(a11*a25);
  a17=(a17-a98);
  a17=(a17/a105);
  a17=(a17*a93);
  a19=(a19+a17);
  a17=casadi_sq(a19);
  a16=(a16+a17);
  a16=sqrt(a16);
  a17=6.3781360000000004e+03;
  a16=(a16-a17);
  a16=(a14*a16);
  a105=11000.;
  a98=(a16<a105);
  a104=1.0129000000000001e+02;
  a111=(a16<a105);
  a112=1.5039999999999999e+01;
  a113=6.4900000000000001e-03;
  a114=(a113*a16);
  a114=(a112-a114);
  a114=(a111?a114:0);
  a111=(!a111);
  a115=(a105<a16);
  a116=25000.;
  a117=(a16<a116);
  a115=(a115&&a117);
  a117=-5.6460000000000001e+01;
  a118=(a115?a117:0);
  a115=(!a115);
  a119=-1.3121000000000001e+02;
  a120=2.9900000000000000e-03;
  a121=(a120*a16);
  a121=(a119+a121);
  a115=(a115?a121:0);
  a118=(a118+a115);
  a111=(a111?a118:0);
  a114=(a114+a111);
  a111=2.7310000000000002e+02;
  a118=(a114+a111);
  a115=2.8807999999999998e+02;
  a118=(a118/a115);
  a121=5.2560000000000002e+00;
  a118=pow(a118,a121);
  a118=(a104*a118);
  a118=(a98?a118:0);
  a98=(!a98);
  a122=(a105<a16);
  a123=(a16<a116);
  a122=(a122&&a123);
  a123=2.2649999999999999e+01;
  a124=1.7300000000000000e+00;
  a125=1.5699999999999999e-04;
  a16=(a125*a16);
  a16=(a124-a16);
  a16=exp(a16);
  a16=(a123*a16);
  a16=(a122?a16:0);
  a122=(!a122);
  a126=2.4880000000000000e+00;
  a127=(a114+a111);
  a128=2.1659999999999999e+02;
  a127=(a127/a128);
  a129=-1.1388000000000000e+01;
  a127=pow(a127,a129);
  a127=(a126*a127);
  a122=(a122?a127:0);
  a16=(a16+a122);
  a98=(a98?a16:0);
  a118=(a118+a98);
  a98=2.8689999999999999e-01;
  a114=(a114+a111);
  a114=(a98*a114);
  a118=(a118/a114);
  a15=(a15*a118);
  a31=casadi_sq(a31);
  a108=casadi_sq(a108);
  a31=(a31+a108);
  a110=casadi_sq(a110);
  a31=(a31+a110);
  a15=(a15*a31);
  a99=(a15*a99);
  a99=(a14*a99);
  a31=-3.1415926535897931e+00;
  a110=casadi_sq(a6);
  a108=casadi_sq(a13);
  a110=(a110+a108);
  a108=casadi_sq(a3);
  a110=(a110+a108);
  a110=sqrt(a110);
  a110=(a110-a17);
  a110=(a14*a110);
  a17=(a110<a105);
  a108=(a110<a105);
  a113=(a113*a110);
  a112=(a112-a113);
  a112=(a108?a112:0);
  a108=(!a108);
  a113=(a105<a110);
  a118=(a110<a116);
  a113=(a113&&a118);
  a117=(a113?a117:0);
  a113=(!a113);
  a120=(a120*a110);
  a119=(a119+a120);
  a113=(a113?a119:0);
  a117=(a117+a113);
  a108=(a108?a117:0);
  a112=(a112+a108);
  a108=(a112+a111);
  a108=(a108/a115);
  a108=pow(a108,a121);
  a104=(a104*a108);
  a104=(a17?a104:0);
  a17=(!a17);
  a105=(a105<a110);
  a116=(a110<a116);
  a105=(a105&&a116);
  a125=(a125*a110);
  a124=(a124-a125);
  a124=exp(a124);
  a123=(a123*a124);
  a123=(a105?a123:0);
  a105=(!a105);
  a124=(a112+a111);
  a124=(a124/a128);
  a124=pow(a124,a129);
  a126=(a126*a124);
  a105=(a105?a126:0);
  a123=(a123+a105);
  a17=(a17?a123:0);
  a104=(a104+a17);
  a112=(a112+a111);
  a98=(a98*a112);
  a104=(a104/a98);
  a31=(a31*a104);
  a104=(a102*a13);
  a104=(a20+a104);
  a98=casadi_sq(a104);
  a102=(a102*a6);
  a102=(a21-a102);
  a112=casadi_sq(a102);
  a98=(a98+a112);
  a112=casadi_sq(a23);
  a98=(a98+a112);
  a31=(a31*a98);
  a98=casadi_sq(a104);
  a112=casadi_sq(a102);
  a98=(a98+a112);
  a112=casadi_sq(a23);
  a98=(a98+a112);
  a98=sqrt(a98);
  a104=(a104/a98);
  a104=(a31*a104);
  a104=(a14*a104);
  a99=(a99-a104);
  a104=(a10*a99);
  a32=(a15*a32);
  a32=(a14*a32);
  a102=(a102/a98);
  a102=(a31*a102);
  a102=(a14*a102);
  a32=(a32-a102);
  a102=(a11*a32);
  a104=(a104+a102);
  a15=(a15*a106);
  a15=(a14*a15);
  a98=(a23/a98);
  a31=(a31*a98);
  a14=(a14*a31);
  a15=(a15-a14);
  a14=(a28*a15);
  a104=(a104+a14);
  a14=(a4*a7);
  a31=(a5*a8);
  a14=(a14+a31);
  a14=(a18*a14);
  a31=casadi_sq(a5);
  a98=casadi_sq(a4);
  a31=(a31-a98);
  a98=casadi_sq(a7);
  a31=(a31-a98);
  a98=casadi_sq(a8);
  a31=(a31+a98);
  a98=(a14*a31);
  a106=(a4*a8);
  a102=(a5*a7);
  a106=(a106-a102);
  a106=(a18*a106);
  a102=(a7*a8);
  a112=(a5*a4);
  a102=(a102-a112);
  a102=(a18*a102);
  a112=(a106*a102);
  a98=(a98-a112);
  a112=casadi_sq(a5);
  a111=casadi_sq(a4);
  a112=(a112+a111);
  a111=casadi_sq(a7);
  a112=(a112-a111);
  a111=casadi_sq(a8);
  a112=(a112-a111);
  a111=casadi_sq(a5);
  a17=casadi_sq(a4);
  a111=(a111-a17);
  a17=casadi_sq(a7);
  a111=(a111+a17);
  a17=casadi_sq(a8);
  a111=(a111-a17);
  a17=(a111*a31);
  a123=(a7*a8);
  a105=(a5*a4);
  a123=(a123+a105);
  a123=(a18*a123);
  a105=(a123*a102);
  a17=(a17-a105);
  a17=(a112*a17);
  a105=(a4*a7);
  a126=(a5*a8);
  a105=(a105-a126);
  a105=(a18*a105);
  a126=(a105*a31);
  a124=(a4*a8);
  a129=(a5*a7);
  a124=(a124+a129);
  a124=(a18*a124);
  a129=(a123*a124);
  a126=(a126-a129);
  a126=(a14*a126);
  a17=(a17-a126);
  a126=(a105*a102);
  a129=(a111*a124);
  a126=(a126-a129);
  a126=(a106*a126);
  a17=(a17+a126);
  a98=(a98/a17);
  a126=1.0000000000000000e-03;
  a129=3.3948485788791928e-02;
  a40=(a40/a41);
  a39=(a39+a40);
  a39=(a39-a43);
  a39=(a39/a44);
  a38=(a38*a39);
  a37=(a37+a38);
  a38=casadi_sq(a39);
  a46=(a46*a38);
  a37=(a37+a46);
  a46=casadi_sq(a39);
  a46=(a46*a39);
  a48=(a48*a46);
  a37=(a37+a48);
  a37=(a36*a37);
  a48=(-a37);
  a48=cos(a48);
  a52=(a52*a39);
  a51=(a51+a52);
  a54=(a54*a38);
  a51=(a51+a54);
  a55=(a55*a46);
  a51=(a51+a55);
  a51=(a36*a51);
  a55=(a51-a37);
  a54=(-a55);
  a54=cos(a54);
  a52=(a48*a54);
  a44=(-a37);
  a44=sin(a44);
  a60=(a60*a39);
  a62=(a62*a38);
  a60=(a60+a62);
  a63=(a63*a46);
  a60=(a60+a63);
  a60=(a36*a60);
  a63=(-a60);
  a63=cos(a63);
  a44=(a44*a63);
  a62=(-a55);
  a62=sin(a62);
  a43=(a44*a62);
  a52=(a52-a43);
  a69=(a69*a39);
  a68=(a68+a69);
  a71=(a71*a38);
  a68=(a68+a71);
  a72=(a72*a46);
  a68=(a68+a72);
  a72=casadi_sq(a68);
  a72=(a67-a72);
  a72=(a66*a72);
  a74=(a74*a39);
  a73=(a73+a74);
  a75=(a75*a38);
  a73=(a73+a75);
  a36=(a36*a73);
  a36=(a36-a51);
  a51=(a18*a68);
  a73=casadi_sq(a68);
  a73=(a68*a73);
  a73=(a73/a76);
  a51=(a51-a73);
  a73=casadi_sq(a68);
  a73=casadi_sq(a73);
  a73=(a68*a73);
  a47=(a47*a73);
  a51=(a51+a47);
  a47=sin(a36);
  a51=(a51*a47);
  a47=casadi_sq(a68);
  a77=(a77*a47);
  a47=casadi_sq(a68);
  a47=casadi_sq(a47);
  a79=(a79*a47);
  a77=(a77-a79);
  a79=(a18*a36);
  a79=sin(a79);
  a77=(a77*a79);
  a51=(a51+a77);
  a77=casadi_sq(a68);
  a77=(a68*a77);
  a78=(a78*a77);
  a77=casadi_sq(a68);
  a77=casadi_sq(a77);
  a77=(a68*a77);
  a81=(a81*a77);
  a78=(a78-a81);
  a81=(a82*a36);
  a81=sin(a81);
  a78=(a78*a81);
  a51=(a51+a78);
  a78=casadi_sq(a68);
  a78=casadi_sq(a78);
  a80=(a80*a78);
  a78=(a76*a36);
  a78=sin(a78);
  a80=(a80*a78);
  a51=(a51+a80);
  a80=casadi_sq(a68);
  a80=casadi_sq(a80);
  a80=(a68*a80);
  a83=(a83*a80);
  a85=(a85*a36);
  a85=sin(a85);
  a83=(a83*a85);
  a51=(a51+a83);
  a36=(a36+a51);
  a51=cos(a36);
  a68=(a68*a51);
  a68=(a67+a68);
  a72=(a72/a68);
  a68=cos(a36);
  a68=(a72*a68);
  a52=(a52*a68);
  a51=(-a55);
  a51=sin(a51);
  a48=(a48*a51);
  a55=(-a55);
  a55=cos(a55);
  a44=(a44*a55);
  a48=(a48+a44);
  a36=sin(a36);
  a72=(a72*a36);
  a48=(a48*a72);
  a52=(a52+a48);
  a52=(a52+a109);
  a109=1.4959787069999999e+08;
  a48=(a52/a109);
  a48=casadi_sq(a48);
  a36=(-a37);
  a36=cos(a36);
  a36=(a36*a63);
  a63=(a36*a55);
  a37=(-a37);
  a37=sin(a37);
  a51=(a37*a51);
  a63=(a63-a51);
  a63=(a63*a72);
  a37=(a37*a54);
  a36=(a36*a62);
  a37=(a37+a36);
  a37=(a37*a68);
  a63=(a63-a37);
  a37=(a88*a63);
  a60=(-a60);
  a60=sin(a60);
  a62=(a60*a62);
  a62=(a62*a68);
  a60=(a60*a55);
  a60=(a60*a72);
  a62=(a62-a60);
  a60=(a57*a62);
  a37=(a37+a60);
  a37=(a37+a97);
  a97=(a37/a109);
  a97=casadi_sq(a97);
  a48=(a48+a97);
  a63=(a49*a63);
  a62=(a88*a62);
  a63=(a63+a62);
  a63=(a63+a19);
  a109=(a63/a109);
  a109=casadi_sq(a109);
  a48=(a48+a109);
  a76=(a76*a48);
  a129=(a129/a76);
  a126=(a126*a129);
  a129=(a4*a8);
  a76=(a5*a7);
  a129=(a129+a76);
  a129=(a18*a129);
  a76=casadi_sq(a52);
  a48=casadi_sq(a37);
  a76=(a76+a48);
  a48=casadi_sq(a63);
  a76=(a76+a48);
  a76=sqrt(a76);
  a52=(a52/a76);
  a129=(a129*a52);
  a48=(a7*a8);
  a109=(a5*a4);
  a48=(a48-a109);
  a48=(a18*a48);
  a37=(a37/a76);
  a48=(a48*a37);
  a129=(a129+a48);
  a48=casadi_sq(a5);
  a109=casadi_sq(a4);
  a48=(a48-a109);
  a109=casadi_sq(a7);
  a48=(a48-a109);
  a109=casadi_sq(a8);
  a48=(a48+a109);
  a63=(a63/a76);
  a48=(a48*a63);
  a129=(a129+a48);
  a126=(a126*a129);
  a48=8.0000000000000004e-01;
  a76=(a4*a7);
  a109=(a5*a8);
  a76=(a76-a109);
  a76=(a18*a76);
  a76=(a76*a52);
  a109=casadi_sq(a5);
  a19=casadi_sq(a4);
  a109=(a109-a19);
  a19=casadi_sq(a7);
  a109=(a109+a19);
  a19=casadi_sq(a8);
  a109=(a109-a19);
  a109=(a109*a37);
  a76=(a76+a109);
  a109=(a7*a8);
  a19=(a5*a4);
  a109=(a109+a19);
  a109=(a18*a109);
  a109=(a109*a63);
  a76=(a76+a109);
  a76=(a48*a76);
  a76=(a126*a76);
  a98=(a98*a76);
  a109=(a111*a31);
  a19=(a123*a102);
  a109=(a109-a19);
  a109=(a109/a17);
  a19=casadi_sq(a5);
  a62=casadi_sq(a4);
  a19=(a19+a62);
  a62=casadi_sq(a7);
  a19=(a19-a62);
  a62=casadi_sq(a8);
  a19=(a19-a62);
  a19=(a19*a52);
  a52=(a4*a7);
  a62=(a5*a8);
  a52=(a52+a62);
  a52=(a18*a52);
  a52=(a52*a37);
  a19=(a19+a52);
  a4=(a4*a8);
  a5=(a5*a7);
  a4=(a4-a5);
  a4=(a18*a4);
  a4=(a4*a63);
  a19=(a19+a4);
  a19=(a48*a19);
  a19=(a126*a19);
  a109=(a109*a19);
  a98=(a98-a109);
  a109=(a14*a123);
  a4=(a106*a111);
  a109=(a109-a4);
  a109=(a109/a17);
  a4=4.0000000000000002e-01;
  a4=(a4*a129);
  a1=(a1-a4);
  a48=(a48*a129);
  a1=(a1-a48);
  a126=(a126*a1);
  a109=(a109*a126);
  a98=(a98+a109);
  a98=(a98+a59);
  a109=(a10*a98);
  a1=(a105*a31);
  a48=(a123*a124);
  a1=(a1-a48);
  a1=(a1/a17);
  a1=(a1*a19);
  a31=(a112*a31);
  a48=(a106*a124);
  a31=(a31-a48);
  a31=(a31/a17);
  a31=(a31*a76);
  a1=(a1-a31);
  a123=(a112*a123);
  a106=(a106*a105);
  a123=(a123-a106);
  a123=(a123/a17);
  a123=(a123*a126);
  a1=(a1-a123);
  a1=(a1+a94);
  a123=(a11*a1);
  a109=(a109+a123);
  a123=(a112*a102);
  a106=(a14*a124);
  a123=(a123-a106);
  a123=(a123/a17);
  a123=(a123*a76);
  a102=(a105*a102);
  a124=(a111*a124);
  a102=(a102-a124);
  a102=(a102/a17);
  a102=(a102*a19);
  a123=(a123-a102);
  a112=(a112*a111);
  a14=(a14*a105);
  a112=(a112-a14);
  a112=(a112/a17);
  a112=(a112*a126);
  a123=(a123+a112);
  a123=(a123+a35);
  a112=(a28*a123);
  a109=(a109+a112);
  a104=(a104+a109);
  a109=-3.9860044150000002e+05;
  a112=casadi_sq(a107);
  a126=casadi_sq(a101);
  a112=(a112+a126);
  a126=casadi_sq(a93);
  a112=(a112+a126);
  a126=sqrt(a112);
  a126=(a126*a112);
  a109=(a109/a126);
  a107=(a109*a107);
  a126=3.9860044150000002e+05;
  a126=(a126/a33);
  a107=(a107+a126);
  a104=(a104+a107);
  a107=-2.;
  a126=(a107*a96);
  a126=(a126*a2);
  a112=(a107*a100);
  a112=(a112*a12);
  a126=(a126-a112);
  a112=(a34*a101);
  a17=(a96*a103);
  a112=(a112-a17);
  a17=(a96*a112);
  a14=(a100*a103);
  a105=(a34*a93);
  a14=(a14-a105);
  a105=(a100*a14);
  a17=(a17-a105);
  a126=(a126-a17);
  a17=(a3*a94);
  a105=(a13*a35);
  a17=(a17-a105);
  a105=(a17/a33);
  a111=(a6*a20);
  a102=(a13*a21);
  a111=(a111+a102);
  a102=(a3*a23);
  a111=(a111+a102);
  a18=(a18*a111);
  a111=(a18*a29);
  a102=casadi_sq(a33);
  a111=(a111/a102);
  a105=(a105-a111);
  a111=(a29*a17);
  a19=(a6*a35);
  a124=(a3*a59);
  a19=(a19-a124);
  a124=(a56*a19);
  a111=(a111+a124);
  a124=(a13*a59);
  a76=(a6*a94);
  a124=(a124-a76);
  a76=(a90*a124);
  a111=(a111+a76);
  a76=(a59*a92);
  a106=(a94*a95);
  a76=(a76+a106);
  a106=(a35*a53);
  a76=(a76+a106);
  a111=(a111*a76);
  a76=(a111*a6);
  a106=(a91*a87);
  a76=(a76/a106);
  a105=(a105+a76);
  a76=1.9094623163594840e+09;
  a31=1.3271244001798700e+11;
  a48=casadi_sq(a70);
  a67=(a67-a48);
  a66=(a66*a67);
  a31=(a31/a66);
  a31=sqrt(a31);
  a66=cos(a42);
  a70=(a70+a66);
  a70=(a31*a70);
  a50=(a50*a70);
  a42=sin(a42);
  a31=(a31*a42);
  a58=(a58*a31);
  a50=(a50-a58);
  a50=(a50+a20);
  a58=(a84*a50);
  a45=(a45*a31);
  a64=(a64*a70);
  a45=(a45+a64);
  a64=(a88*a45);
  a65=(a65*a31);
  a61=(a61*a70);
  a65=(a65+a61);
  a57=(a57*a65);
  a64=(a64-a57);
  a64=(a64+a21);
  a57=(a89*a64);
  a58=(a58+a57);
  a49=(a49*a45);
  a88=(a88*a65);
  a49=(a49-a88);
  a49=(a49+a23);
  a88=(a86*a49);
  a58=(a58+a88);
  a82=(a82*a58);
  a58=(a82*a84);
  a84=casadi_sq(a84);
  a88=casadi_sq(a89);
  a84=(a84+a88);
  a88=casadi_sq(a86);
  a84=(a84+a88);
  a88=sqrt(a84);
  a65=casadi_sq(a84);
  a65=(a88*a65);
  a58=(a58/a65);
  a88=(a88*a84);
  a50=(a50/a88);
  a58=(a58-a50);
  a58=(a76*a58);
  a58=(a58*a92);
  a89=(a82*a89);
  a89=(a89/a65);
  a64=(a64/a88);
  a89=(a89-a64);
  a89=(a76*a89);
  a89=(a89*a95);
  a58=(a58+a89);
  a82=(a82*a86);
  a82=(a82/a65);
  a49=(a49/a88);
  a82=(a82-a49);
  a76=(a76*a82);
  a76=(a76*a53);
  a58=(a58+a76);
  a76=(a17/a91);
  a17=(a29*a17);
  a82=(a56*a19);
  a17=(a17+a82);
  a82=(a90*a124);
  a17=(a17+a82);
  a29=(a17*a29);
  a87=(a91*a87);
  a29=(a29/a87);
  a76=(a76-a29);
  a76=(a59*a76);
  a29=(a19/a91);
  a82=(a17*a56);
  a82=(a82/a87);
  a29=(a29-a82);
  a29=(a94*a29);
  a76=(a76+a29);
  a29=(a124/a91);
  a17=(a17*a90);
  a17=(a17/a87);
  a29=(a29-a17);
  a29=(a35*a29);
  a76=(a76+a29);
  a58=(a58-a76);
  a6=(a58*a6);
  a6=(a6/a91);
  a105=(a105+a6);
  a59=(a59*a92);
  a94=(a94*a95);
  a59=(a59+a94);
  a35=(a35*a53);
  a59=(a59+a35);
  a20=(a59*a20);
  a20=(a20/a91);
  a105=(a105-a20);
  a20=(a25*a105);
  a19=(a19/a33);
  a56=(a18*a56);
  a56=(a56/a102);
  a19=(a19-a56);
  a56=(a111*a13);
  a56=(a56/a106);
  a19=(a19+a56);
  a13=(a58*a13);
  a13=(a13/a91);
  a19=(a19+a13);
  a21=(a59*a21);
  a21=(a21/a91);
  a19=(a19-a21);
  a21=(a27*a19);
  a20=(a20+a21);
  a124=(a124/a33);
  a18=(a18*a90);
  a18=(a18/a102);
  a124=(a124-a18);
  a111=(a111*a3);
  a111=(a111/a106);
  a124=(a124+a111);
  a58=(a58*a3);
  a58=(a58/a91);
  a124=(a124+a58);
  a59=(a59*a23);
  a59=(a59/a91);
  a124=(a124-a59);
  a59=(a30*a124);
  a20=(a20+a59);
  a59=(a20*a93);
  a91=(a24*a105);
  a23=(a26*a19);
  a91=(a91+a23);
  a23=(a22*a124);
  a91=(a91+a23);
  a23=(a91*a101);
  a59=(a59-a23);
  a126=(a126-a59);
  a104=(a104+a126);
  a104=(a0*a104);
  if (res[0]!=0) res[0][10]=a104;
  a104=(a25*a99);
  a126=(a27*a32);
  a104=(a104+a126);
  a126=(a30*a15);
  a104=(a104+a126);
  a25=(a25*a98);
  a27=(a27*a1);
  a25=(a25+a27);
  a30=(a30*a123);
  a25=(a25+a30);
  a104=(a104+a25);
  a25=(a109*a101);
  a104=(a104+a25);
  a25=(a107*a100);
  a25=(a25*a9);
  a30=(a107*a34);
  a30=(a30*a2);
  a25=(a25-a30);
  a30=(a96*a93);
  a2=(a100*a101);
  a30=(a30-a2);
  a100=(a100*a30);
  a112=(a34*a112);
  a100=(a100-a112);
  a25=(a25-a100);
  a91=(a91*a103);
  a10=(a10*a105);
  a11=(a11*a19);
  a10=(a10+a11);
  a28=(a28*a124);
  a10=(a10+a28);
  a28=(a10*a93);
  a91=(a91-a28);
  a25=(a25-a91);
  a104=(a104+a25);
  a104=(a0*a104);
  if (res[0]!=0) res[0][11]=a104;
  a99=(a24*a99);
  a32=(a26*a32);
  a99=(a99+a32);
  a15=(a22*a15);
  a99=(a99+a15);
  a24=(a24*a98);
  a26=(a26*a1);
  a24=(a24+a26);
  a22=(a22*a123);
  a24=(a24+a22);
  a99=(a99+a24);
  a109=(a109*a93);
  a99=(a99+a109);
  a109=(a107*a34);
  a109=(a109*a12);
  a107=(a107*a96);
  a107=(a107*a9);
  a109=(a109-a107);
  a34=(a34*a14);
  a96=(a96*a30);
  a34=(a34-a96);
  a109=(a109-a34);
  a10=(a10*a101);
  a20=(a20*a103);
  a10=(a10-a20);
  a109=(a109-a10);
  a99=(a99+a109);
  a0=(a0*a99);
  if (res[0]!=0) res[0][12]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int fdrift(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int fdrift_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int fdrift_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fdrift_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int fdrift_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fdrift_release(int mem) {
}

CASADI_SYMBOL_EXPORT void fdrift_incref(void) {
}

CASADI_SYMBOL_EXPORT void fdrift_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fdrift_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int fdrift_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real fdrift_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fdrift_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fdrift_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fdrift_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fdrift_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fdrift_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_fdrift(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[163];
  casadi_int *iw = 0;
  const casadi_real* arg[3] = {0};
  casadi_real* res[1] = {0};
  if (argc>3) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"fdrift\" failed. Too many input arguments (%d, max 3)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"fdrift\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+33);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+1, casadi_s1, w+33);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+14, casadi_s2, w+33);
  --resc;
  res[0] = w+20;
  i = fdrift(arg, res, iw, w+33, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"fdrift\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s1, res[0]);
}
#endif

casadi_int main_fdrift(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[163];
  const casadi_real* arg[3];
  casadi_real* res[1];
  arg[0] = w+0;
  arg[1] = w+1;
  arg[2] = w+14;
  res[0] = w+20;
  a = w;
  for (j=0; j<20; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = fdrift(arg, res, iw, w+33, 0);
  if (flag) return flag;
  r = w+20;
  for (j=0; j<13; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[7];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_fdrift(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "fdrift")==0) {
    mex_fdrift(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'fdrift'");
}
#endif
int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "fdrift")==0) {
    return main_fdrift(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'fdrift'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
