/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) L_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[17] = {13, 1, 0, 13, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

/* L:(X[13],dX[13],k1,k2,k3,t,XChief[6])->(CurveLength) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a100, a101, a102, a103, a104, a105, a106, a107, a108, a109, a11, a110, a111, a112, a113, a114, a115, a116, a117, a118, a119, a12, a120, a121, a122, a123, a124, a125, a126, a127, a128, a129, a13, a130, a131, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a64, a65, a66, a67, a68, a69, a7, a70, a71, a72, a73, a74, a75, a76, a77, a78, a79, a8, a80, a81, a82, a83, a84, a85, a86, a87, a88, a89, a9, a90, a91, a92, a93, a94, a95, a96, a97, a98, a99;
  a0=arg[1]? arg[1][0] : 0;
  a1=1.7839223988857496e+05;
  a2=5.0000000000000000e-01;
  a3=arg[0]? arg[0][4] : 0;
  a4=(a2*a3);
  a5=arg[0]? arg[0][1] : 0;
  a6=arg[0]? arg[0][0] : 0;
  a7=casadi_sq(a6);
  a8=casadi_sq(a5);
  a7=(a7+a8);
  a8=arg[0]? arg[0][2] : 0;
  a9=casadi_sq(a8);
  a7=(a7+a9);
  a9=arg[0]? arg[0][3] : 0;
  a10=casadi_sq(a9);
  a7=(a7+a10);
  a7=sqrt(a7);
  a5=(a5/a7);
  a4=(a4*a5);
  a10=arg[0]? arg[0][5] : 0;
  a11=(a2*a10);
  a8=(a8/a7);
  a11=(a11*a8);
  a4=(a4+a11);
  a11=arg[0]? arg[0][6] : 0;
  a12=(a2*a11);
  a9=(a9/a7);
  a12=(a12*a9);
  a4=(a4+a12);
  a4=(a1*a4);
  a12=(a0+a4);
  a13=arg[2]? arg[2][0] : 0;
  a12=(a12*a13);
  a0=(a0+a4);
  a12=(a12*a0);
  a0=arg[1]? arg[1][1] : 0;
  a4=(a2*a3);
  a6=(a6/a7);
  a4=(a4*a6);
  a7=(a2*a11);
  a7=(a7*a8);
  a4=(a4+a7);
  a7=(a2*a10);
  a7=(a7*a9);
  a4=(a4-a7);
  a4=(a1*a4);
  a7=(a0-a4);
  a7=(a7*a13);
  a0=(a0-a4);
  a7=(a7*a0);
  a12=(a12+a7);
  a7=arg[1]? arg[1][2] : 0;
  a0=(a2*a10);
  a0=(a0*a6);
  a4=(a2*a11);
  a4=(a4*a5);
  a0=(a0-a4);
  a4=(a2*a3);
  a4=(a4*a9);
  a0=(a0+a4);
  a0=(a1*a0);
  a4=(a7-a0);
  a4=(a4*a13);
  a7=(a7-a0);
  a4=(a4*a7);
  a12=(a12+a4);
  a4=arg[1]? arg[1][3] : 0;
  a7=(a2*a11);
  a7=(a7*a6);
  a0=(a2*a10);
  a0=(a0*a5);
  a7=(a7+a0);
  a0=(a2*a3);
  a0=(a0*a8);
  a7=(a7-a0);
  a7=(a1*a7);
  a0=(a4-a7);
  a0=(a0*a13);
  a4=(a4-a7);
  a0=(a0*a4);
  a12=(a12+a0);
  a0=6.9444444444444426e+05;
  a4=arg[1]? arg[1][4] : 0;
  a7=8.3333333333333326e+02;
  a13=(a7*a10);
  a14=(a11*a13);
  a15=1.6666666666666665e+03;
  a16=(a15*a11);
  a17=(a10*a16);
  a14=(a14-a17);
  a14=(a14/a7);
  a14=(a1*a14);
  a17=(a4-a14);
  a17=(a0*a17);
  a4=(a4-a14);
  a17=(a17*a4);
  a12=(a12+a17);
  a17=arg[1]? arg[1][5] : 0;
  a16=(a3*a16);
  a4=(a7*a3);
  a11=(a11*a4);
  a16=(a16-a11);
  a16=(a16/a7);
  a16=(a1*a16);
  a7=(a17-a16);
  a0=(a0*a7);
  a17=(a17-a16);
  a0=(a0*a17);
  a12=(a12+a0);
  a0=2.7777777777777771e+06;
  a17=arg[1]? arg[1][6] : 0;
  a10=(a10*a4);
  a3=(a3*a13);
  a10=(a10-a3);
  a10=(a10/a15);
  a10=(a1*a10);
  a15=(a17-a10);
  a0=(a0*a15);
  a17=(a17-a10);
  a0=(a0*a17);
  a12=(a12+a0);
  a0=arg[1]? arg[1][7] : 0;
  a17=arg[0]? arg[0][10] : 0;
  a10=(a1*a17);
  a15=(a0-a10);
  a3=arg[3]? arg[3][0] : 0;
  a15=(a15*a3);
  a0=(a0-a10);
  a15=(a15*a0);
  a12=(a12+a15);
  a15=arg[1]? arg[1][8] : 0;
  a0=arg[0]? arg[0][11] : 0;
  a10=(a1*a0);
  a13=(a15-a10);
  a13=(a13*a3);
  a15=(a15-a10);
  a13=(a13*a15);
  a12=(a12+a13);
  a13=arg[1]? arg[1][9] : 0;
  a15=arg[0]? arg[0][12] : 0;
  a10=(a1*a15);
  a4=(a13-a10);
  a4=(a4*a3);
  a13=(a13-a10);
  a4=(a4*a13);
  a12=(a12+a4);
  a4=arg[1]? arg[1][10] : 0;
  a13=arg[6]? arg[6][0] : 0;
  a10=casadi_sq(a13);
  a3=arg[6]? arg[6][1] : 0;
  a16=casadi_sq(a3);
  a10=(a10+a16);
  a16=arg[6]? arg[6][2] : 0;
  a7=casadi_sq(a16);
  a10=(a10+a7);
  a10=sqrt(a10);
  a7=(a13/a10);
  a11=1000.;
  a14=-6.4000000000000001e-01;
  a18=2.5000000000000000e-01;
  a19=2500.;
  a20=2.;
  a21=(a5*a9);
  a22=(a6*a8);
  a21=(a21+a22);
  a21=(a20*a21);
  a21=(a19*a21);
  a22=arg[6]? arg[6][3] : 0;
  a23=arg[6]? arg[6][4] : 0;
  a24=(a13*a23);
  a25=(a3*a22);
  a24=(a24-a25);
  a25=arg[6]? arg[6][5] : 0;
  a26=(a3*a25);
  a27=(a16*a23);
  a26=(a26-a27);
  a27=casadi_sq(a26);
  a28=(a16*a22);
  a29=(a13*a25);
  a28=(a28-a29);
  a29=casadi_sq(a28);
  a27=(a27+a29);
  a29=casadi_sq(a24);
  a27=(a27+a29);
  a27=sqrt(a27);
  a24=(a24/a27);
  a29=(a24*a7);
  a26=(a26/a27);
  a30=(a16/a10);
  a31=(a26*a30);
  a29=(a29-a31);
  a28=(a28/a27);
  a27=(a28*a30);
  a10=(a3/a10);
  a31=(a24*a10);
  a27=(a27-a31);
  a31=casadi_sq(a27);
  a32=casadi_sq(a29);
  a31=(a31+a32);
  a32=(a26*a10);
  a33=(a28*a7);
  a32=(a32-a33);
  a33=casadi_sq(a32);
  a31=(a31+a33);
  a31=sqrt(a31);
  a29=(a29/a31);
  a33=(a29*a24);
  a32=(a32/a31);
  a34=(a32*a28);
  a33=(a33-a34);
  a34=(a29*a24);
  a35=(a32*a28);
  a34=(a34-a35);
  a34=(a7*a34);
  a27=(a27/a31);
  a31=(a27*a24);
  a35=(a32*a26);
  a31=(a31-a35);
  a31=(a10*a31);
  a34=(a34-a31);
  a31=(a27*a28);
  a35=(a29*a26);
  a31=(a31-a35);
  a31=(a30*a31);
  a34=(a34+a31);
  a33=(a33/a34);
  a31=(a3*a25);
  a35=(a16*a23);
  a31=(a31-a35);
  a35=casadi_sq(a13);
  a36=casadi_sq(a3);
  a35=(a35+a36);
  a36=casadi_sq(a16);
  a35=(a35+a36);
  a36=(a31/a35);
  a37=-1.9094623163594840e+09;
  a38=1.7453292519943295e-02;
  a39=1.7487317400000001e+02;
  a40=-2.4109079999999999e-01;
  a41=2.4562962500000000e+06;
  a42=arg[5]? arg[5][0] : 0;
  a42=(a1*a42);
  a43=86400.;
  a44=(a42/a43);
  a44=(a41+a44);
  a45=2451545.;
  a44=(a44-a45);
  a46=36525.;
  a44=(a44/a46);
  a47=(a40*a44);
  a47=(a39+a47);
  a48=4.0670000000000002e-05;
  a49=casadi_sq(a44);
  a50=(a48*a49);
  a47=(a47+a50);
  a50=-1.3270000000000000e-06;
  a51=casadi_sq(a44);
  a51=(a51*a44);
  a52=(a50*a51);
  a47=(a47+a52);
  a47=(a38*a47);
  a52=(-a47);
  a52=cos(a52);
  a53=1.0293734800000000e+02;
  a54=3.2255570000000000e-01;
  a55=(a54*a44);
  a55=(a53+a55);
  a56=1.5025999999999999e-04;
  a57=(a56*a49);
  a55=(a55+a57);
  a57=4.7800000000000002e-07;
  a58=(a57*a51);
  a55=(a55+a58);
  a55=(a38*a55);
  a58=(a55-a47);
  a59=(-a58);
  a59=cos(a59);
  a60=(a52*a59);
  a61=(-a47);
  a61=sin(a61);
  a62=1.3054600000000000e-02;
  a63=(a62*a44);
  a64=-9.3100000000000006e-06;
  a65=(a64*a49);
  a63=(a63+a65);
  a65=-3.4000000000000000e-08;
  a66=(a65*a51);
  a63=(a63+a66);
  a63=(a38*a63);
  a66=(-a63);
  a66=cos(a66);
  a61=(a61*a66);
  a67=(-a58);
  a67=sin(a67);
  a68=(a61*a67);
  a60=(a60-a68);
  a68=1.4959802299063239e+08;
  a69=1.;
  a70=1.6708620000000000e-02;
  a71=-4.2036999999999997e-05;
  a72=(a71*a44);
  a72=(a70+a72);
  a73=-1.2360000000000000e-07;
  a74=(a73*a49);
  a72=(a72+a74);
  a74=3.9999999999999998e-11;
  a51=(a74*a51);
  a72=(a72+a51);
  a51=casadi_sq(a72);
  a51=(a69-a51);
  a51=(a68*a51);
  a75=1.0046644900000000e+02;
  a76=3.5999372851900000e+04;
  a44=(a76*a44);
  a44=(a75+a44);
  a77=-5.6799999999999998e-06;
  a49=(a77*a49);
  a44=(a44+a49);
  a44=(a38*a44);
  a44=(a44-a55);
  a55=(a20*a72);
  a49=casadi_sq(a72);
  a49=(a72*a49);
  a78=4.;
  a49=(a49/a78);
  a55=(a55-a49);
  a49=5.2083333333333336e-02;
  a79=casadi_sq(a72);
  a79=casadi_sq(a79);
  a79=(a72*a79);
  a79=(a49*a79);
  a55=(a55+a79);
  a79=sin(a44);
  a55=(a55*a79);
  a79=1.2500000000000000e+00;
  a80=casadi_sq(a72);
  a80=(a79*a80);
  a81=4.5833333333333331e-01;
  a82=casadi_sq(a72);
  a82=casadi_sq(a82);
  a82=(a81*a82);
  a80=(a80-a82);
  a82=(a20*a44);
  a82=sin(a82);
  a80=(a80*a82);
  a55=(a55+a80);
  a80=1.0833333333333333e+00;
  a82=casadi_sq(a72);
  a82=(a72*a82);
  a82=(a80*a82);
  a83=6.7187500000000000e-01;
  a84=casadi_sq(a72);
  a84=casadi_sq(a84);
  a84=(a72*a84);
  a84=(a83*a84);
  a82=(a82-a84);
  a84=3.;
  a85=(a84*a44);
  a85=sin(a85);
  a82=(a82*a85);
  a55=(a55+a82);
  a82=1.0729166666666667e+00;
  a85=casadi_sq(a72);
  a85=casadi_sq(a85);
  a85=(a82*a85);
  a86=(a78*a44);
  a86=sin(a86);
  a85=(a85*a86);
  a55=(a55+a85);
  a85=1.1427083333333334e+00;
  a86=casadi_sq(a72);
  a86=casadi_sq(a86);
  a86=(a72*a86);
  a86=(a85*a86);
  a87=5.;
  a88=(a87*a44);
  a88=sin(a88);
  a86=(a86*a88);
  a55=(a55+a86);
  a44=(a44+a55);
  a55=cos(a44);
  a55=(a72*a55);
  a55=(a69+a55);
  a51=(a51/a55);
  a55=cos(a44);
  a55=(a51*a55);
  a86=(a60*a55);
  a88=(-a58);
  a88=sin(a88);
  a52=(a52*a88);
  a58=(-a58);
  a58=cos(a58);
  a61=(a61*a58);
  a52=(a52+a61);
  a61=sin(a44);
  a51=(a51*a61);
  a61=(a52*a51);
  a86=(a86+a61);
  a86=(a86+a13);
  a61=(a37*a86);
  a89=casadi_sq(a86);
  a90=9.1748200035787253e-01;
  a91=(-a47);
  a91=cos(a91);
  a91=(a91*a66);
  a66=(a91*a58);
  a47=(-a47);
  a47=sin(a47);
  a88=(a47*a88);
  a66=(a66-a88);
  a88=(a66*a51);
  a47=(a47*a59);
  a91=(a91*a67);
  a47=(a47+a91);
  a91=(a47*a55);
  a88=(a88-a91);
  a91=(a90*a88);
  a59=-3.9777729827042280e-01;
  a63=(-a63);
  a63=sin(a63);
  a67=(a63*a67);
  a55=(a67*a55);
  a63=(a63*a58);
  a51=(a63*a51);
  a55=(a55-a51);
  a51=(a59*a55);
  a91=(a91+a51);
  a91=(a91+a3);
  a51=casadi_sq(a91);
  a89=(a89+a51);
  a51=3.9777729827042280e-01;
  a88=(a51*a88);
  a55=(a90*a55);
  a88=(a88+a55);
  a88=(a88+a16);
  a55=casadi_sq(a88);
  a89=(a89+a55);
  a55=sqrt(a89);
  a55=(a55*a89);
  a61=(a61/a55);
  a89=casadi_sq(a31);
  a58=(a16*a22);
  a92=(a13*a25);
  a58=(a58-a92);
  a92=casadi_sq(a58);
  a89=(a89+a92);
  a92=(a13*a23);
  a93=(a3*a22);
  a92=(a92-a93);
  a93=casadi_sq(a92);
  a89=(a89+a93);
  a93=sqrt(a89);
  a94=(a31/a93);
  a95=(a61*a94);
  a96=(a37*a91);
  a96=(a96/a55);
  a97=(a58/a93);
  a98=(a96*a97);
  a95=(a95+a98);
  a37=(a37*a88);
  a37=(a37/a55);
  a55=(a92/a93);
  a98=(a37*a55);
  a95=(a95+a98);
  a98=(a95*a13);
  a98=(a98/a93);
  a36=(a36-a98);
  a98=(a27*a36);
  a99=(a58/a35);
  a100=(a95*a3);
  a100=(a100/a93);
  a99=(a99-a100);
  a100=(a29*a99);
  a98=(a98+a100);
  a100=(a92/a35);
  a95=(a95*a16);
  a95=(a95/a93);
  a100=(a100-a95);
  a95=(a32*a100);
  a98=(a98+a95);
  a95=arg[0]? arg[0][9] : 0;
  a101=(a98*a95);
  a102=(a26*a36);
  a103=(a28*a99);
  a102=(a102+a103);
  a103=(a24*a100);
  a102=(a102+a103);
  a103=arg[0]? arg[0][8] : 0;
  a104=(a102*a103);
  a101=(a101-a104);
  a101=(a17+a101);
  a33=(a33*a101);
  a104=(a10*a24);
  a105=(a30*a28);
  a104=(a104-a105);
  a104=(a104/a34);
  a105=arg[0]? arg[0][7] : 0;
  a106=(a102*a105);
  a36=(a7*a36);
  a99=(a10*a99);
  a36=(a36+a99);
  a100=(a30*a100);
  a36=(a36+a100);
  a100=(a36*a95);
  a106=(a106-a100);
  a106=(a0+a106);
  a104=(a104*a106);
  a33=(a33-a104);
  a104=(a10*a32);
  a100=(a30*a29);
  a104=(a104-a100);
  a104=(a104/a34);
  a100=(a36*a103);
  a99=(a98*a105);
  a100=(a100-a99);
  a100=(a15+a100);
  a104=(a104*a100);
  a33=(a33+a104);
  a33=(a22+a33);
  a104=7.2921240000000005e-05;
  a99=(a7*a24);
  a107=(a30*a26);
  a99=(a99-a107);
  a107=(a29*a24);
  a108=(a32*a28);
  a107=(a107-a108);
  a107=(a7*a107);
  a108=(a27*a24);
  a109=(a32*a26);
  a108=(a108-a109);
  a108=(a10*a108);
  a107=(a107-a108);
  a108=(a27*a28);
  a109=(a29*a26);
  a108=(a108-a109);
  a108=(a30*a108);
  a107=(a107+a108);
  a99=(a99/a107);
  a99=(a99*a103);
  a108=(a27*a24);
  a109=(a32*a26);
  a108=(a108-a109);
  a108=(a108/a107);
  a109=sqrt(a35);
  a109=(a109+a105);
  a108=(a108*a109);
  a99=(a99-a108);
  a108=(a7*a32);
  a110=(a30*a27);
  a108=(a108-a110);
  a108=(a108/a107);
  a108=(a108*a95);
  a99=(a99-a108);
  a108=(a104*a99);
  a33=(a33+a108);
  a108=casadi_sq(a33);
  a110=(a7*a24);
  a111=(a30*a26);
  a110=(a110-a111);
  a110=(a110/a34);
  a110=(a110*a106);
  a111=(a27*a24);
  a112=(a32*a26);
  a111=(a111-a112);
  a111=(a111/a34);
  a111=(a111*a101);
  a110=(a110-a111);
  a111=(a7*a32);
  a112=(a30*a27);
  a111=(a111-a112);
  a111=(a111/a34);
  a111=(a111*a100);
  a110=(a110-a111);
  a110=(a23+a110);
  a111=(a29*a24);
  a112=(a32*a28);
  a111=(a111-a112);
  a111=(a111/a107);
  a111=(a111*a109);
  a112=(a10*a24);
  a113=(a30*a28);
  a112=(a112-a113);
  a112=(a112/a107);
  a112=(a112*a103);
  a111=(a111-a112);
  a112=(a10*a32);
  a113=(a30*a29);
  a112=(a112-a113);
  a112=(a112/a107);
  a112=(a112*a95);
  a111=(a111+a112);
  a112=(a104*a111);
  a110=(a110-a112);
  a112=casadi_sq(a110);
  a108=(a108+a112);
  a112=(a27*a28);
  a113=(a29*a26);
  a112=(a112-a113);
  a112=(a112/a34);
  a112=(a112*a101);
  a101=(a7*a28);
  a113=(a10*a26);
  a101=(a101-a113);
  a101=(a101/a34);
  a101=(a101*a106);
  a112=(a112-a101);
  a101=(a7*a29);
  a106=(a10*a27);
  a101=(a101-a106);
  a101=(a101/a34);
  a101=(a101*a100);
  a112=(a112+a101);
  a112=(a25+a112);
  a101=casadi_sq(a112);
  a108=(a108+a101);
  a108=sqrt(a108);
  a101=(a33/a108);
  a21=(a21*a101);
  a100=(a8*a9);
  a34=(a6*a5);
  a100=(a100-a34);
  a100=(a20*a100);
  a100=(a19*a100);
  a34=(a110/a108);
  a100=(a100*a34);
  a21=(a21+a100);
  a100=casadi_sq(a6);
  a106=casadi_sq(a5);
  a100=(a100-a106);
  a106=casadi_sq(a8);
  a100=(a100-a106);
  a106=casadi_sq(a9);
  a100=(a100+a106);
  a19=(a19*a100);
  a108=(a112/a108);
  a19=(a19*a108);
  a21=(a21+a19);
  a21=fabs(a21);
  a18=(a18*a21);
  a14=(a14*a18);
  a18=casadi_sq(a111);
  a21=casadi_sq(a99);
  a18=(a18+a21);
  a21=(a27*a28);
  a19=(a29*a26);
  a21=(a21-a19);
  a21=(a21/a107);
  a21=(a21*a109);
  a19=(a7*a28);
  a100=(a10*a26);
  a19=(a19-a100);
  a19=(a19/a107);
  a19=(a19*a103);
  a21=(a21-a19);
  a19=(a7*a29);
  a100=(a10*a27);
  a19=(a19-a100);
  a19=(a19/a107);
  a19=(a19*a95);
  a21=(a21+a19);
  a19=casadi_sq(a21);
  a18=(a18+a19);
  a18=sqrt(a18);
  a19=6.3781360000000004e+03;
  a18=(a18-a19);
  a18=(a11*a18);
  a107=11000.;
  a100=(a18<a107);
  a106=1.0129000000000001e+02;
  a113=(a18<a107);
  a114=1.5039999999999999e+01;
  a115=6.4900000000000001e-03;
  a116=(a115*a18);
  a116=(a114-a116);
  a116=(a113?a116:0);
  a113=(!a113);
  a117=(a107<a18);
  a118=25000.;
  a119=(a18<a118);
  a117=(a117&&a119);
  a119=-5.6460000000000001e+01;
  a120=(a117?a119:0);
  a117=(!a117);
  a121=-1.3121000000000001e+02;
  a122=2.9900000000000000e-03;
  a123=(a122*a18);
  a123=(a121+a123);
  a117=(a117?a123:0);
  a120=(a120+a117);
  a113=(a113?a120:0);
  a116=(a116+a113);
  a113=2.7310000000000002e+02;
  a120=(a116+a113);
  a117=2.8807999999999998e+02;
  a120=(a120/a117);
  a123=5.2560000000000002e+00;
  a120=pow(a120,a123);
  a120=(a106*a120);
  a120=(a100?a120:0);
  a100=(!a100);
  a124=(a107<a18);
  a125=(a18<a118);
  a124=(a124&&a125);
  a125=2.2649999999999999e+01;
  a126=1.7300000000000000e+00;
  a127=1.5699999999999999e-04;
  a18=(a127*a18);
  a18=(a126-a18);
  a18=exp(a18);
  a18=(a125*a18);
  a18=(a124?a18:0);
  a124=(!a124);
  a128=2.4880000000000000e+00;
  a129=(a116+a113);
  a130=2.1659999999999999e+02;
  a129=(a129/a130);
  a131=-1.1388000000000000e+01;
  a129=pow(a129,a131);
  a129=(a128*a129);
  a124=(a124?a129:0);
  a18=(a18+a124);
  a100=(a100?a18:0);
  a120=(a120+a100);
  a100=2.8689999999999999e-01;
  a116=(a116+a113);
  a116=(a100*a116);
  a120=(a120/a116);
  a14=(a14*a120);
  a33=casadi_sq(a33);
  a110=casadi_sq(a110);
  a33=(a33+a110);
  a112=casadi_sq(a112);
  a33=(a33+a112);
  a14=(a14*a33);
  a101=(a14*a101);
  a101=(a11*a101);
  a33=-3.1415926535897931e+00;
  a112=casadi_sq(a13);
  a110=casadi_sq(a3);
  a112=(a112+a110);
  a110=casadi_sq(a16);
  a112=(a112+a110);
  a112=sqrt(a112);
  a112=(a112-a19);
  a112=(a11*a112);
  a19=(a112<a107);
  a110=(a112<a107);
  a115=(a115*a112);
  a114=(a114-a115);
  a114=(a110?a114:0);
  a110=(!a110);
  a115=(a107<a112);
  a120=(a112<a118);
  a115=(a115&&a120);
  a119=(a115?a119:0);
  a115=(!a115);
  a122=(a122*a112);
  a121=(a121+a122);
  a115=(a115?a121:0);
  a119=(a119+a115);
  a110=(a110?a119:0);
  a114=(a114+a110);
  a110=(a114+a113);
  a110=(a110/a117);
  a110=pow(a110,a123);
  a106=(a106*a110);
  a106=(a19?a106:0);
  a19=(!a19);
  a107=(a107<a112);
  a118=(a112<a118);
  a107=(a107&&a118);
  a127=(a127*a112);
  a126=(a126-a127);
  a126=exp(a126);
  a125=(a125*a126);
  a125=(a107?a125:0);
  a107=(!a107);
  a126=(a114+a113);
  a126=(a126/a130);
  a126=pow(a126,a131);
  a128=(a128*a126);
  a107=(a107?a128:0);
  a125=(a125+a107);
  a19=(a19?a125:0);
  a106=(a106+a19);
  a114=(a114+a113);
  a100=(a100*a114);
  a106=(a106/a100);
  a33=(a33*a106);
  a106=(a104*a3);
  a106=(a22+a106);
  a100=casadi_sq(a106);
  a104=(a104*a13);
  a104=(a23-a104);
  a114=casadi_sq(a104);
  a100=(a100+a114);
  a114=casadi_sq(a25);
  a100=(a100+a114);
  a33=(a33*a100);
  a100=casadi_sq(a106);
  a114=casadi_sq(a104);
  a100=(a100+a114);
  a114=casadi_sq(a25);
  a100=(a100+a114);
  a100=sqrt(a100);
  a106=(a106/a100);
  a106=(a33*a106);
  a106=(a11*a106);
  a101=(a101-a106);
  a106=(a7*a101);
  a34=(a14*a34);
  a34=(a11*a34);
  a104=(a104/a100);
  a104=(a33*a104);
  a104=(a11*a104);
  a34=(a34-a104);
  a104=(a10*a34);
  a106=(a106+a104);
  a14=(a14*a108);
  a14=(a11*a14);
  a100=(a25/a100);
  a33=(a33*a100);
  a11=(a11*a33);
  a14=(a14-a11);
  a11=(a30*a14);
  a106=(a106+a11);
  a11=(a5*a8);
  a33=(a6*a9);
  a11=(a11+a33);
  a11=(a20*a11);
  a33=casadi_sq(a6);
  a100=casadi_sq(a5);
  a33=(a33-a100);
  a100=casadi_sq(a8);
  a33=(a33-a100);
  a100=casadi_sq(a9);
  a33=(a33+a100);
  a100=(a11*a33);
  a108=(a5*a9);
  a104=(a6*a8);
  a108=(a108-a104);
  a108=(a20*a108);
  a104=(a8*a9);
  a114=(a6*a5);
  a104=(a104-a114);
  a104=(a20*a104);
  a114=(a108*a104);
  a100=(a100-a114);
  a114=casadi_sq(a6);
  a113=casadi_sq(a5);
  a114=(a114+a113);
  a113=casadi_sq(a8);
  a114=(a114-a113);
  a113=casadi_sq(a9);
  a114=(a114-a113);
  a113=casadi_sq(a6);
  a19=casadi_sq(a5);
  a113=(a113-a19);
  a19=casadi_sq(a8);
  a113=(a113+a19);
  a19=casadi_sq(a9);
  a113=(a113-a19);
  a19=(a113*a33);
  a125=(a8*a9);
  a107=(a6*a5);
  a125=(a125+a107);
  a125=(a20*a125);
  a107=(a125*a104);
  a19=(a19-a107);
  a19=(a114*a19);
  a107=(a5*a8);
  a128=(a6*a9);
  a107=(a107-a128);
  a107=(a20*a107);
  a128=(a107*a33);
  a126=(a5*a9);
  a131=(a6*a8);
  a126=(a126+a131);
  a126=(a20*a126);
  a131=(a125*a126);
  a128=(a128-a131);
  a128=(a11*a128);
  a19=(a19-a128);
  a128=(a107*a104);
  a131=(a113*a126);
  a128=(a128-a131);
  a128=(a108*a128);
  a19=(a19+a128);
  a100=(a100/a19);
  a128=1.0000000000000000e-03;
  a131=3.3948485788791928e-02;
  a42=(a42/a43);
  a41=(a41+a42);
  a41=(a41-a45);
  a41=(a41/a46);
  a40=(a40*a41);
  a39=(a39+a40);
  a40=casadi_sq(a41);
  a48=(a48*a40);
  a39=(a39+a48);
  a48=casadi_sq(a41);
  a48=(a48*a41);
  a50=(a50*a48);
  a39=(a39+a50);
  a39=(a38*a39);
  a50=(-a39);
  a50=cos(a50);
  a54=(a54*a41);
  a53=(a53+a54);
  a56=(a56*a40);
  a53=(a53+a56);
  a57=(a57*a48);
  a53=(a53+a57);
  a53=(a38*a53);
  a57=(a53-a39);
  a56=(-a57);
  a56=cos(a56);
  a54=(a50*a56);
  a46=(-a39);
  a46=sin(a46);
  a62=(a62*a41);
  a64=(a64*a40);
  a62=(a62+a64);
  a65=(a65*a48);
  a62=(a62+a65);
  a62=(a38*a62);
  a65=(-a62);
  a65=cos(a65);
  a46=(a46*a65);
  a64=(-a57);
  a64=sin(a64);
  a45=(a46*a64);
  a54=(a54-a45);
  a71=(a71*a41);
  a70=(a70+a71);
  a73=(a73*a40);
  a70=(a70+a73);
  a74=(a74*a48);
  a70=(a70+a74);
  a74=casadi_sq(a70);
  a74=(a69-a74);
  a74=(a68*a74);
  a76=(a76*a41);
  a75=(a75+a76);
  a77=(a77*a40);
  a75=(a75+a77);
  a38=(a38*a75);
  a38=(a38-a53);
  a53=(a20*a70);
  a75=casadi_sq(a70);
  a75=(a70*a75);
  a75=(a75/a78);
  a53=(a53-a75);
  a75=casadi_sq(a70);
  a75=casadi_sq(a75);
  a75=(a70*a75);
  a49=(a49*a75);
  a53=(a53+a49);
  a49=sin(a38);
  a53=(a53*a49);
  a49=casadi_sq(a70);
  a79=(a79*a49);
  a49=casadi_sq(a70);
  a49=casadi_sq(a49);
  a81=(a81*a49);
  a79=(a79-a81);
  a81=(a20*a38);
  a81=sin(a81);
  a79=(a79*a81);
  a53=(a53+a79);
  a79=casadi_sq(a70);
  a79=(a70*a79);
  a80=(a80*a79);
  a79=casadi_sq(a70);
  a79=casadi_sq(a79);
  a79=(a70*a79);
  a83=(a83*a79);
  a80=(a80-a83);
  a83=(a84*a38);
  a83=sin(a83);
  a80=(a80*a83);
  a53=(a53+a80);
  a80=casadi_sq(a70);
  a80=casadi_sq(a80);
  a82=(a82*a80);
  a80=(a78*a38);
  a80=sin(a80);
  a82=(a82*a80);
  a53=(a53+a82);
  a82=casadi_sq(a70);
  a82=casadi_sq(a82);
  a82=(a70*a82);
  a85=(a85*a82);
  a87=(a87*a38);
  a87=sin(a87);
  a85=(a85*a87);
  a53=(a53+a85);
  a38=(a38+a53);
  a53=cos(a38);
  a70=(a70*a53);
  a70=(a69+a70);
  a74=(a74/a70);
  a70=cos(a38);
  a70=(a74*a70);
  a54=(a54*a70);
  a53=(-a57);
  a53=sin(a53);
  a50=(a50*a53);
  a57=(-a57);
  a57=cos(a57);
  a46=(a46*a57);
  a50=(a50+a46);
  a38=sin(a38);
  a74=(a74*a38);
  a50=(a50*a74);
  a54=(a54+a50);
  a54=(a54+a111);
  a111=1.4959787069999999e+08;
  a50=(a54/a111);
  a50=casadi_sq(a50);
  a38=(-a39);
  a38=cos(a38);
  a38=(a38*a65);
  a65=(a38*a57);
  a39=(-a39);
  a39=sin(a39);
  a53=(a39*a53);
  a65=(a65-a53);
  a65=(a65*a74);
  a39=(a39*a56);
  a38=(a38*a64);
  a39=(a39+a38);
  a39=(a39*a70);
  a65=(a65-a39);
  a39=(a90*a65);
  a62=(-a62);
  a62=sin(a62);
  a64=(a62*a64);
  a64=(a64*a70);
  a62=(a62*a57);
  a62=(a62*a74);
  a64=(a64-a62);
  a62=(a59*a64);
  a39=(a39+a62);
  a39=(a39+a99);
  a99=(a39/a111);
  a99=casadi_sq(a99);
  a50=(a50+a99);
  a65=(a51*a65);
  a64=(a90*a64);
  a65=(a65+a64);
  a65=(a65+a21);
  a111=(a65/a111);
  a111=casadi_sq(a111);
  a50=(a50+a111);
  a78=(a78*a50);
  a131=(a131/a78);
  a128=(a128*a131);
  a131=(a5*a9);
  a78=(a6*a8);
  a131=(a131+a78);
  a131=(a20*a131);
  a78=casadi_sq(a54);
  a50=casadi_sq(a39);
  a78=(a78+a50);
  a50=casadi_sq(a65);
  a78=(a78+a50);
  a78=sqrt(a78);
  a54=(a54/a78);
  a131=(a131*a54);
  a50=(a8*a9);
  a111=(a6*a5);
  a50=(a50-a111);
  a50=(a20*a50);
  a39=(a39/a78);
  a50=(a50*a39);
  a131=(a131+a50);
  a50=casadi_sq(a6);
  a111=casadi_sq(a5);
  a50=(a50-a111);
  a111=casadi_sq(a8);
  a50=(a50-a111);
  a111=casadi_sq(a9);
  a50=(a50+a111);
  a65=(a65/a78);
  a50=(a50*a65);
  a131=(a131+a50);
  a128=(a128*a131);
  a50=8.0000000000000004e-01;
  a78=(a5*a8);
  a111=(a6*a9);
  a78=(a78-a111);
  a78=(a20*a78);
  a78=(a78*a54);
  a111=casadi_sq(a6);
  a21=casadi_sq(a5);
  a111=(a111-a21);
  a21=casadi_sq(a8);
  a111=(a111+a21);
  a21=casadi_sq(a9);
  a111=(a111-a21);
  a111=(a111*a39);
  a78=(a78+a111);
  a111=(a8*a9);
  a21=(a6*a5);
  a111=(a111+a21);
  a111=(a20*a111);
  a111=(a111*a65);
  a78=(a78+a111);
  a78=(a50*a78);
  a78=(a128*a78);
  a100=(a100*a78);
  a111=(a113*a33);
  a21=(a125*a104);
  a111=(a111-a21);
  a111=(a111/a19);
  a21=casadi_sq(a6);
  a64=casadi_sq(a5);
  a21=(a21+a64);
  a64=casadi_sq(a8);
  a21=(a21-a64);
  a64=casadi_sq(a9);
  a21=(a21-a64);
  a21=(a21*a54);
  a54=(a5*a8);
  a64=(a6*a9);
  a54=(a54+a64);
  a54=(a20*a54);
  a54=(a54*a39);
  a21=(a21+a54);
  a5=(a5*a9);
  a6=(a6*a8);
  a5=(a5-a6);
  a5=(a20*a5);
  a5=(a5*a65);
  a21=(a21+a5);
  a21=(a50*a21);
  a21=(a128*a21);
  a111=(a111*a21);
  a100=(a100-a111);
  a111=(a11*a125);
  a5=(a108*a113);
  a111=(a111-a5);
  a111=(a111/a19);
  a5=4.0000000000000002e-01;
  a5=(a5*a131);
  a2=(a2-a5);
  a50=(a50*a131);
  a2=(a2-a50);
  a128=(a128*a2);
  a111=(a111*a128);
  a100=(a100+a111);
  a100=(a100+a61);
  a111=(a7*a100);
  a2=(a107*a33);
  a50=(a125*a126);
  a2=(a2-a50);
  a2=(a2/a19);
  a2=(a2*a21);
  a33=(a114*a33);
  a50=(a108*a126);
  a33=(a33-a50);
  a33=(a33/a19);
  a33=(a33*a78);
  a2=(a2-a33);
  a125=(a114*a125);
  a108=(a108*a107);
  a125=(a125-a108);
  a125=(a125/a19);
  a125=(a125*a128);
  a2=(a2-a125);
  a2=(a2+a96);
  a125=(a10*a2);
  a111=(a111+a125);
  a125=(a114*a104);
  a108=(a11*a126);
  a125=(a125-a108);
  a125=(a125/a19);
  a125=(a125*a78);
  a104=(a107*a104);
  a126=(a113*a126);
  a104=(a104-a126);
  a104=(a104/a19);
  a104=(a104*a21);
  a125=(a125-a104);
  a114=(a114*a113);
  a11=(a11*a107);
  a114=(a114-a11);
  a114=(a114/a19);
  a114=(a114*a128);
  a125=(a125+a114);
  a125=(a125+a37);
  a114=(a30*a125);
  a111=(a111+a114);
  a106=(a106+a111);
  a111=-3.9860044150000002e+05;
  a114=casadi_sq(a109);
  a128=casadi_sq(a103);
  a114=(a114+a128);
  a128=casadi_sq(a95);
  a114=(a114+a128);
  a128=sqrt(a114);
  a128=(a128*a114);
  a111=(a111/a128);
  a109=(a111*a109);
  a128=3.9860044150000002e+05;
  a128=(a128/a35);
  a109=(a109+a128);
  a106=(a106+a109);
  a109=-2.;
  a128=(a109*a98);
  a128=(a128*a15);
  a114=(a109*a102);
  a114=(a114*a0);
  a128=(a128-a114);
  a114=(a36*a103);
  a19=(a98*a105);
  a114=(a114-a19);
  a19=(a98*a114);
  a11=(a102*a105);
  a107=(a36*a95);
  a11=(a11-a107);
  a107=(a102*a11);
  a19=(a19-a107);
  a128=(a128-a19);
  a19=(a16*a96);
  a107=(a3*a37);
  a19=(a19-a107);
  a107=(a19/a35);
  a113=(a13*a22);
  a104=(a3*a23);
  a113=(a113+a104);
  a104=(a16*a25);
  a113=(a113+a104);
  a20=(a20*a113);
  a113=(a20*a31);
  a104=casadi_sq(a35);
  a113=(a113/a104);
  a107=(a107-a113);
  a113=(a31*a19);
  a21=(a13*a37);
  a126=(a16*a61);
  a21=(a21-a126);
  a126=(a58*a21);
  a113=(a113+a126);
  a126=(a3*a61);
  a78=(a13*a96);
  a126=(a126-a78);
  a78=(a92*a126);
  a113=(a113+a78);
  a78=(a61*a94);
  a108=(a96*a97);
  a78=(a78+a108);
  a108=(a37*a55);
  a78=(a78+a108);
  a113=(a113*a78);
  a78=(a113*a13);
  a108=(a93*a89);
  a78=(a78/a108);
  a107=(a107+a78);
  a78=1.9094623163594840e+09;
  a33=1.3271244001798700e+11;
  a50=casadi_sq(a72);
  a69=(a69-a50);
  a68=(a68*a69);
  a33=(a33/a68);
  a33=sqrt(a33);
  a68=cos(a44);
  a72=(a72+a68);
  a72=(a33*a72);
  a52=(a52*a72);
  a44=sin(a44);
  a33=(a33*a44);
  a60=(a60*a33);
  a52=(a52-a60);
  a52=(a52+a22);
  a60=(a86*a52);
  a47=(a47*a33);
  a66=(a66*a72);
  a47=(a47+a66);
  a66=(a90*a47);
  a67=(a67*a33);
  a63=(a63*a72);
  a67=(a67+a63);
  a59=(a59*a67);
  a66=(a66-a59);
  a66=(a66+a23);
  a59=(a91*a66);
  a60=(a60+a59);
  a51=(a51*a47);
  a90=(a90*a67);
  a51=(a51-a90);
  a51=(a51+a25);
  a90=(a88*a51);
  a60=(a60+a90);
  a84=(a84*a60);
  a60=(a84*a86);
  a86=casadi_sq(a86);
  a90=casadi_sq(a91);
  a86=(a86+a90);
  a90=casadi_sq(a88);
  a86=(a86+a90);
  a90=sqrt(a86);
  a67=casadi_sq(a86);
  a67=(a90*a67);
  a60=(a60/a67);
  a90=(a90*a86);
  a52=(a52/a90);
  a60=(a60-a52);
  a60=(a78*a60);
  a60=(a60*a94);
  a91=(a84*a91);
  a91=(a91/a67);
  a66=(a66/a90);
  a91=(a91-a66);
  a91=(a78*a91);
  a91=(a91*a97);
  a60=(a60+a91);
  a84=(a84*a88);
  a84=(a84/a67);
  a51=(a51/a90);
  a84=(a84-a51);
  a78=(a78*a84);
  a78=(a78*a55);
  a60=(a60+a78);
  a78=(a19/a93);
  a19=(a31*a19);
  a84=(a58*a21);
  a19=(a19+a84);
  a84=(a92*a126);
  a19=(a19+a84);
  a31=(a19*a31);
  a89=(a93*a89);
  a31=(a31/a89);
  a78=(a78-a31);
  a78=(a61*a78);
  a31=(a21/a93);
  a84=(a19*a58);
  a84=(a84/a89);
  a31=(a31-a84);
  a31=(a96*a31);
  a78=(a78+a31);
  a31=(a126/a93);
  a19=(a19*a92);
  a19=(a19/a89);
  a31=(a31-a19);
  a31=(a37*a31);
  a78=(a78+a31);
  a60=(a60-a78);
  a13=(a60*a13);
  a13=(a13/a93);
  a107=(a107+a13);
  a61=(a61*a94);
  a96=(a96*a97);
  a61=(a61+a96);
  a37=(a37*a55);
  a61=(a61+a37);
  a22=(a61*a22);
  a22=(a22/a93);
  a107=(a107-a22);
  a22=(a27*a107);
  a21=(a21/a35);
  a58=(a20*a58);
  a58=(a58/a104);
  a21=(a21-a58);
  a58=(a113*a3);
  a58=(a58/a108);
  a21=(a21+a58);
  a3=(a60*a3);
  a3=(a3/a93);
  a21=(a21+a3);
  a23=(a61*a23);
  a23=(a23/a93);
  a21=(a21-a23);
  a23=(a29*a21);
  a22=(a22+a23);
  a126=(a126/a35);
  a20=(a20*a92);
  a20=(a20/a104);
  a126=(a126-a20);
  a113=(a113*a16);
  a113=(a113/a108);
  a126=(a126+a113);
  a60=(a60*a16);
  a60=(a60/a93);
  a126=(a126+a60);
  a61=(a61*a25);
  a61=(a61/a93);
  a126=(a126-a61);
  a61=(a32*a126);
  a22=(a22+a61);
  a61=(a22*a95);
  a93=(a26*a107);
  a25=(a28*a21);
  a93=(a93+a25);
  a25=(a24*a126);
  a93=(a93+a25);
  a25=(a93*a103);
  a61=(a61-a25);
  a128=(a128-a61);
  a106=(a106+a128);
  a106=(a1*a106);
  a128=(a4-a106);
  a61=arg[4]? arg[4][0] : 0;
  a128=(a128*a61);
  a4=(a4-a106);
  a128=(a128*a4);
  a12=(a12+a128);
  a128=arg[1]? arg[1][11] : 0;
  a4=(a27*a101);
  a106=(a29*a34);
  a4=(a4+a106);
  a106=(a32*a14);
  a4=(a4+a106);
  a27=(a27*a100);
  a29=(a29*a2);
  a27=(a27+a29);
  a32=(a32*a125);
  a27=(a27+a32);
  a4=(a4+a27);
  a27=(a111*a103);
  a4=(a4+a27);
  a27=(a109*a102);
  a27=(a27*a17);
  a32=(a109*a36);
  a32=(a32*a15);
  a27=(a27-a32);
  a32=(a98*a95);
  a15=(a102*a103);
  a32=(a32-a15);
  a102=(a102*a32);
  a114=(a36*a114);
  a102=(a102-a114);
  a27=(a27-a102);
  a93=(a93*a105);
  a7=(a7*a107);
  a10=(a10*a21);
  a7=(a7+a10);
  a30=(a30*a126);
  a7=(a7+a30);
  a30=(a7*a95);
  a93=(a93-a30);
  a27=(a27-a93);
  a4=(a4+a27);
  a4=(a1*a4);
  a27=(a128-a4);
  a27=(a27*a61);
  a128=(a128-a4);
  a27=(a27*a128);
  a12=(a12+a27);
  a27=arg[1]? arg[1][12] : 0;
  a101=(a26*a101);
  a34=(a28*a34);
  a101=(a101+a34);
  a14=(a24*a14);
  a101=(a101+a14);
  a26=(a26*a100);
  a28=(a28*a2);
  a26=(a26+a28);
  a24=(a24*a125);
  a26=(a26+a24);
  a101=(a101+a26);
  a111=(a111*a95);
  a101=(a101+a111);
  a111=(a109*a36);
  a111=(a111*a0);
  a109=(a109*a98);
  a109=(a109*a17);
  a111=(a111-a109);
  a36=(a36*a11);
  a98=(a98*a32);
  a36=(a36-a98);
  a111=(a111-a36);
  a7=(a7*a103);
  a22=(a22*a105);
  a7=(a7-a22);
  a111=(a111-a7);
  a101=(a101+a111);
  a1=(a1*a101);
  a101=(a27-a1);
  a101=(a101*a61);
  a27=(a27-a1);
  a101=(a101*a27);
  a12=(a12+a101);
  if (res[0]!=0) res[0][0]=a12;
  return 0;
}

CASADI_SYMBOL_EXPORT int L(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int L_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int L_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void L_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int L_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void L_release(int mem) {
}

CASADI_SYMBOL_EXPORT void L_incref(void) {
}

CASADI_SYMBOL_EXPORT void L_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int L_n_in(void) { return 7;}

CASADI_SYMBOL_EXPORT casadi_int L_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real L_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* L_name_in(casadi_int i){
  switch (i) {
    case 0: return "X";
    case 1: return "dX";
    case 2: return "k1";
    case 3: return "k2";
    case 4: return "k3";
    case 5: return "t";
    case 6: return "XChief";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* L_name_out(casadi_int i){
  switch (i) {
    case 0: return "CurveLength";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* L_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s1;
    case 5: return casadi_s1;
    case 6: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* L_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int L_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_L(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[169];
  casadi_int *iw = 0;
  const casadi_real* arg[7] = {0};
  casadi_real* res[1] = {0};
  if (argc>7) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"L\" failed. Too many input arguments (%d, max 7)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"L\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+37);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+13, casadi_s0, w+37);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+26, casadi_s1, w+37);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+27, casadi_s1, w+37);
  if (--argc>=0) arg[4] = casadi_from_mex(argv[4], w+28, casadi_s1, w+37);
  if (--argc>=0) arg[5] = casadi_from_mex(argv[5], w+29, casadi_s1, w+37);
  if (--argc>=0) arg[6] = casadi_from_mex(argv[6], w+30, casadi_s2, w+37);
  --resc;
  res[0] = w+36;
  i = L(arg, res, iw, w+37, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"L\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s1, res[0]);
}
#endif

casadi_int main_L(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[169];
  const casadi_real* arg[7];
  casadi_real* res[1];
  arg[0] = w+0;
  arg[1] = w+13;
  arg[2] = w+26;
  arg[3] = w+27;
  arg[4] = w+28;
  arg[5] = w+29;
  arg[6] = w+30;
  res[0] = w+36;
  a = w;
  for (j=0; j<36; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = L(arg, res, iw, w+37, 0);
  if (flag) return flag;
  r = w+36;
  for (j=0; j<1; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[2];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_L(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "L")==0) {
    mex_L(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'L'");
}
#endif
int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "L")==0) {
    return main_L(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'L'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
