/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) fdrift_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s1[40] = {36, 1, 0, 36, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35};
static const casadi_int casadi_s2[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};

/* fdrift:(i0,i1[36],i2[6])->(o0[36]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a5, a6, a7, a8, a9;
  a0=1.6840054676261389e+04;
  a1=arg[1]? arg[1][3] : 0;
  a2=(a0*a1);
  if (res[0]!=0) res[0][0]=a2;
  a2=arg[1]? arg[1][4] : 0;
  a3=(a0*a2);
  if (res[0]!=0) res[0][1]=a3;
  a3=arg[1]? arg[1][5] : 0;
  a4=(a0*a3);
  if (res[0]!=0) res[0][2]=a4;
  a4=-3.9860044150000002e+05;
  a5=arg[2]? arg[2][0] : 0;
  a6=casadi_sq(a5);
  a7=arg[2]? arg[2][1] : 0;
  a8=casadi_sq(a7);
  a6=(a6+a8);
  a8=arg[2]? arg[2][2] : 0;
  a9=casadi_sq(a8);
  a6=(a6+a9);
  a9=sqrt(a6);
  a10=arg[1]? arg[1][0] : 0;
  a11=(a9+a10);
  a12=casadi_sq(a11);
  a13=arg[1]? arg[1][1] : 0;
  a14=casadi_sq(a13);
  a12=(a12+a14);
  a14=arg[1]? arg[1][2] : 0;
  a15=casadi_sq(a14);
  a12=(a12+a15);
  a15=1.5000000000000000e+00;
  a12=pow(a12,a15);
  a12=(a4/a12);
  a11=(a12*a11);
  a16=3.9860044150000002e+05;
  a17=(a16/a6);
  a11=(a11+a17);
  a17=-2.;
  a18=arg[2]? arg[2][3] : 0;
  a19=(a8*a18);
  a20=arg[2]? arg[2][5] : 0;
  a21=(a5*a20);
  a19=(a19-a21);
  a21=(a7*a20);
  a22=arg[2]? arg[2][4] : 0;
  a23=(a8*a22);
  a21=(a21-a23);
  a23=casadi_sq(a21);
  a24=casadi_sq(a19);
  a23=(a23+a24);
  a24=(a5*a22);
  a25=(a7*a18);
  a24=(a24-a25);
  a25=casadi_sq(a24);
  a23=(a23+a25);
  a23=sqrt(a23);
  a19=(a19/a23);
  a25=casadi_sq(a5);
  a26=casadi_sq(a7);
  a25=(a25+a26);
  a26=casadi_sq(a8);
  a25=(a25+a26);
  a25=sqrt(a25);
  a26=(a8/a25);
  a27=(a19*a26);
  a24=(a24/a23);
  a28=(a7/a25);
  a29=(a24*a28);
  a27=(a27-a29);
  a29=casadi_sq(a27);
  a25=(a5/a25);
  a30=(a24*a25);
  a21=(a21/a23);
  a23=(a21*a26);
  a30=(a30-a23);
  a23=casadi_sq(a30);
  a29=(a29+a23);
  a23=(a21*a28);
  a31=(a19*a25);
  a23=(a23-a31);
  a31=casadi_sq(a23);
  a29=(a29+a31);
  a29=sqrt(a29);
  a27=(a27/a29);
  a31=(a7*a20);
  a32=(a8*a22);
  a31=(a31-a32);
  a32=(a31/a6);
  a33=(a27*a32);
  a30=(a30/a29);
  a34=(a8*a18);
  a35=(a5*a20);
  a34=(a34-a35);
  a35=(a34/a6);
  a36=(a30*a35);
  a33=(a33+a36);
  a23=(a23/a29);
  a29=(a5*a22);
  a36=(a7*a18);
  a29=(a29-a36);
  a36=(a29/a6);
  a37=(a23*a36);
  a33=(a33+a37);
  a37=(a17*a33);
  a38=(a37*a3);
  a39=(a21*a32);
  a40=(a19*a35);
  a39=(a39+a40);
  a40=(a24*a36);
  a39=(a39+a40);
  a40=(a17*a39);
  a41=(a40*a2);
  a38=(a38-a41);
  a32=(a25*a32);
  a35=(a28*a35);
  a32=(a32+a35);
  a36=(a26*a36);
  a32=(a32+a36);
  a36=(a32*a13);
  a35=(a33*a10);
  a36=(a36-a35);
  a35=(a33*a36);
  a41=(a39*a10);
  a42=(a32*a14);
  a41=(a41-a42);
  a42=(a39*a41);
  a35=(a35-a42);
  a38=(a38-a35);
  a5=(a5*a18);
  a7=(a7*a22);
  a5=(a5+a7);
  a8=(a8*a20);
  a5=(a5+a8);
  a5=(a17*a5);
  a31=(a5*a31);
  a8=casadi_sq(a6);
  a31=(a31/a8);
  a27=(a27*a31);
  a34=(a5*a34);
  a34=(a34/a8);
  a30=(a30*a34);
  a27=(a27+a30);
  a5=(a5*a29);
  a5=(a5/a8);
  a23=(a23*a5);
  a27=(a27+a23);
  a23=(a27*a14);
  a21=(a21*a31);
  a19=(a19*a34);
  a21=(a21+a19);
  a24=(a24*a5);
  a21=(a21+a24);
  a24=(a21*a13);
  a23=(a23-a24);
  a38=(a38-a23);
  a11=(a11+a38);
  a11=(a0*a11);
  if (res[0]!=0) res[0][3]=a11;
  a11=(a12*a13);
  a38=(a17*a39);
  a23=(a38*a1);
  a24=(a17*a32);
  a3=(a24*a3);
  a23=(a23-a3);
  a3=(a33*a14);
  a19=(a39*a13);
  a3=(a3-a19);
  a19=(a39*a3);
  a36=(a32*a36);
  a19=(a19-a36);
  a23=(a23-a19);
  a19=(a21*a10);
  a25=(a25*a31);
  a28=(a28*a34);
  a25=(a25+a28);
  a26=(a26*a5);
  a25=(a25+a26);
  a26=(a25*a14);
  a19=(a19-a26);
  a23=(a23-a19);
  a11=(a11+a23);
  a11=(a0*a11);
  if (res[0]!=0) res[0][4]=a11;
  a12=(a12*a14);
  a14=(a17*a32);
  a2=(a14*a2);
  a17=(a17*a33);
  a1=(a17*a1);
  a2=(a2-a1);
  a41=(a32*a41);
  a3=(a33*a3);
  a41=(a41-a3);
  a2=(a2-a41);
  a13=(a25*a13);
  a10=(a27*a10);
  a13=(a13-a10);
  a2=(a2-a13);
  a12=(a12+a2);
  a12=(a0*a12);
  if (res[0]!=0) res[0][5]=a12;
  a12=arg[1]? arg[1][9] : 0;
  a2=(a0*a12);
  if (res[0]!=0) res[0][6]=a2;
  a2=arg[1]? arg[1][10] : 0;
  a13=(a0*a2);
  if (res[0]!=0) res[0][7]=a13;
  a13=arg[1]? arg[1][11] : 0;
  a10=(a0*a13);
  if (res[0]!=0) res[0][8]=a10;
  a10=arg[1]? arg[1][6] : 0;
  a41=(a9+a10);
  a3=casadi_sq(a41);
  a1=arg[1]? arg[1][7] : 0;
  a11=casadi_sq(a1);
  a3=(a3+a11);
  a11=arg[1]? arg[1][8] : 0;
  a23=casadi_sq(a11);
  a3=(a3+a23);
  a3=pow(a3,a15);
  a3=(a4/a3);
  a41=(a3*a41);
  a23=(a16/a6);
  a41=(a41+a23);
  a23=(a37*a13);
  a19=(a40*a2);
  a23=(a23-a19);
  a19=(a32*a1);
  a26=(a33*a10);
  a19=(a19-a26);
  a26=(a33*a19);
  a5=(a39*a10);
  a28=(a32*a11);
  a5=(a5-a28);
  a28=(a39*a5);
  a26=(a26-a28);
  a23=(a23-a26);
  a26=(a27*a11);
  a28=(a21*a1);
  a26=(a26-a28);
  a23=(a23-a26);
  a41=(a41+a23);
  a41=(a0*a41);
  if (res[0]!=0) res[0][9]=a41;
  a41=(a3*a1);
  a23=(a38*a12);
  a13=(a24*a13);
  a23=(a23-a13);
  a13=(a33*a11);
  a26=(a39*a1);
  a13=(a13-a26);
  a26=(a39*a13);
  a19=(a32*a19);
  a26=(a26-a19);
  a23=(a23-a26);
  a26=(a21*a10);
  a19=(a25*a11);
  a26=(a26-a19);
  a23=(a23-a26);
  a41=(a41+a23);
  a41=(a0*a41);
  if (res[0]!=0) res[0][10]=a41;
  a3=(a3*a11);
  a2=(a14*a2);
  a12=(a17*a12);
  a2=(a2-a12);
  a5=(a32*a5);
  a13=(a33*a13);
  a5=(a5-a13);
  a2=(a2-a5);
  a1=(a25*a1);
  a10=(a27*a10);
  a1=(a1-a10);
  a2=(a2-a1);
  a3=(a3+a2);
  a3=(a0*a3);
  if (res[0]!=0) res[0][11]=a3;
  a3=arg[1]? arg[1][15] : 0;
  a2=(a0*a3);
  if (res[0]!=0) res[0][12]=a2;
  a2=arg[1]? arg[1][16] : 0;
  a1=(a0*a2);
  if (res[0]!=0) res[0][13]=a1;
  a1=arg[1]? arg[1][17] : 0;
  a10=(a0*a1);
  if (res[0]!=0) res[0][14]=a10;
  a10=arg[1]? arg[1][12] : 0;
  a5=(a9+a10);
  a13=casadi_sq(a5);
  a12=arg[1]? arg[1][13] : 0;
  a11=casadi_sq(a12);
  a13=(a13+a11);
  a11=arg[1]? arg[1][14] : 0;
  a41=casadi_sq(a11);
  a13=(a13+a41);
  a13=pow(a13,a15);
  a13=(a4/a13);
  a5=(a13*a5);
  a41=(a16/a6);
  a5=(a5+a41);
  a41=(a37*a1);
  a23=(a40*a2);
  a41=(a41-a23);
  a23=(a32*a12);
  a26=(a33*a10);
  a23=(a23-a26);
  a26=(a33*a23);
  a19=(a39*a10);
  a28=(a32*a11);
  a19=(a19-a28);
  a28=(a39*a19);
  a26=(a26-a28);
  a41=(a41-a26);
  a26=(a27*a11);
  a28=(a21*a12);
  a26=(a26-a28);
  a41=(a41-a26);
  a5=(a5+a41);
  a5=(a0*a5);
  if (res[0]!=0) res[0][15]=a5;
  a5=(a13*a12);
  a41=(a38*a3);
  a1=(a24*a1);
  a41=(a41-a1);
  a1=(a33*a11);
  a26=(a39*a12);
  a1=(a1-a26);
  a26=(a39*a1);
  a23=(a32*a23);
  a26=(a26-a23);
  a41=(a41-a26);
  a26=(a21*a10);
  a23=(a25*a11);
  a26=(a26-a23);
  a41=(a41-a26);
  a5=(a5+a41);
  a5=(a0*a5);
  if (res[0]!=0) res[0][16]=a5;
  a13=(a13*a11);
  a2=(a14*a2);
  a3=(a17*a3);
  a2=(a2-a3);
  a19=(a32*a19);
  a1=(a33*a1);
  a19=(a19-a1);
  a2=(a2-a19);
  a12=(a25*a12);
  a10=(a27*a10);
  a12=(a12-a10);
  a2=(a2-a12);
  a13=(a13+a2);
  a13=(a0*a13);
  if (res[0]!=0) res[0][17]=a13;
  a13=arg[1]? arg[1][21] : 0;
  a2=(a0*a13);
  if (res[0]!=0) res[0][18]=a2;
  a2=arg[1]? arg[1][22] : 0;
  a12=(a0*a2);
  if (res[0]!=0) res[0][19]=a12;
  a12=arg[1]? arg[1][23] : 0;
  a10=(a0*a12);
  if (res[0]!=0) res[0][20]=a10;
  a10=arg[1]? arg[1][18] : 0;
  a19=(a9+a10);
  a1=casadi_sq(a19);
  a3=arg[1]? arg[1][19] : 0;
  a11=casadi_sq(a3);
  a1=(a1+a11);
  a11=arg[1]? arg[1][20] : 0;
  a5=casadi_sq(a11);
  a1=(a1+a5);
  a1=pow(a1,a15);
  a1=(a4/a1);
  a19=(a1*a19);
  a5=(a16/a6);
  a19=(a19+a5);
  a5=(a37*a12);
  a41=(a40*a2);
  a5=(a5-a41);
  a41=(a32*a3);
  a26=(a33*a10);
  a41=(a41-a26);
  a26=(a33*a41);
  a23=(a39*a10);
  a28=(a32*a11);
  a23=(a23-a28);
  a28=(a39*a23);
  a26=(a26-a28);
  a5=(a5-a26);
  a26=(a27*a11);
  a28=(a21*a3);
  a26=(a26-a28);
  a5=(a5-a26);
  a19=(a19+a5);
  a19=(a0*a19);
  if (res[0]!=0) res[0][21]=a19;
  a19=(a1*a3);
  a5=(a38*a13);
  a12=(a24*a12);
  a5=(a5-a12);
  a12=(a33*a11);
  a26=(a39*a3);
  a12=(a12-a26);
  a26=(a39*a12);
  a41=(a32*a41);
  a26=(a26-a41);
  a5=(a5-a26);
  a26=(a21*a10);
  a41=(a25*a11);
  a26=(a26-a41);
  a5=(a5-a26);
  a19=(a19+a5);
  a19=(a0*a19);
  if (res[0]!=0) res[0][22]=a19;
  a1=(a1*a11);
  a2=(a14*a2);
  a13=(a17*a13);
  a2=(a2-a13);
  a23=(a32*a23);
  a12=(a33*a12);
  a23=(a23-a12);
  a2=(a2-a23);
  a3=(a25*a3);
  a10=(a27*a10);
  a3=(a3-a10);
  a2=(a2-a3);
  a1=(a1+a2);
  a1=(a0*a1);
  if (res[0]!=0) res[0][23]=a1;
  a1=arg[1]? arg[1][27] : 0;
  a2=(a0*a1);
  if (res[0]!=0) res[0][24]=a2;
  a2=arg[1]? arg[1][28] : 0;
  a3=(a0*a2);
  if (res[0]!=0) res[0][25]=a3;
  a3=arg[1]? arg[1][29] : 0;
  a10=(a0*a3);
  if (res[0]!=0) res[0][26]=a10;
  a10=arg[1]? arg[1][24] : 0;
  a23=(a9+a10);
  a12=casadi_sq(a23);
  a13=arg[1]? arg[1][25] : 0;
  a11=casadi_sq(a13);
  a12=(a12+a11);
  a11=arg[1]? arg[1][26] : 0;
  a19=casadi_sq(a11);
  a12=(a12+a19);
  a12=pow(a12,a15);
  a12=(a4/a12);
  a23=(a12*a23);
  a19=(a16/a6);
  a23=(a23+a19);
  a19=(a37*a3);
  a5=(a40*a2);
  a19=(a19-a5);
  a5=(a32*a13);
  a26=(a33*a10);
  a5=(a5-a26);
  a26=(a33*a5);
  a41=(a39*a10);
  a28=(a32*a11);
  a41=(a41-a28);
  a28=(a39*a41);
  a26=(a26-a28);
  a19=(a19-a26);
  a26=(a27*a11);
  a28=(a21*a13);
  a26=(a26-a28);
  a19=(a19-a26);
  a23=(a23+a19);
  a23=(a0*a23);
  if (res[0]!=0) res[0][27]=a23;
  a23=(a12*a13);
  a19=(a38*a1);
  a3=(a24*a3);
  a19=(a19-a3);
  a3=(a33*a11);
  a26=(a39*a13);
  a3=(a3-a26);
  a26=(a39*a3);
  a5=(a32*a5);
  a26=(a26-a5);
  a19=(a19-a26);
  a26=(a21*a10);
  a5=(a25*a11);
  a26=(a26-a5);
  a19=(a19-a26);
  a23=(a23+a19);
  a23=(a0*a23);
  if (res[0]!=0) res[0][28]=a23;
  a12=(a12*a11);
  a2=(a14*a2);
  a1=(a17*a1);
  a2=(a2-a1);
  a41=(a32*a41);
  a3=(a33*a3);
  a41=(a41-a3);
  a2=(a2-a41);
  a13=(a25*a13);
  a10=(a27*a10);
  a13=(a13-a10);
  a2=(a2-a13);
  a12=(a12+a2);
  a12=(a0*a12);
  if (res[0]!=0) res[0][29]=a12;
  a12=arg[1]? arg[1][33] : 0;
  a2=(a0*a12);
  if (res[0]!=0) res[0][30]=a2;
  a2=arg[1]? arg[1][34] : 0;
  a13=(a0*a2);
  if (res[0]!=0) res[0][31]=a13;
  a13=arg[1]? arg[1][35] : 0;
  a10=(a0*a13);
  if (res[0]!=0) res[0][32]=a10;
  a10=arg[1]? arg[1][30] : 0;
  a9=(a9+a10);
  a41=casadi_sq(a9);
  a3=arg[1]? arg[1][31] : 0;
  a1=casadi_sq(a3);
  a41=(a41+a1);
  a1=arg[1]? arg[1][32] : 0;
  a11=casadi_sq(a1);
  a41=(a41+a11);
  a41=pow(a41,a15);
  a4=(a4/a41);
  a9=(a4*a9);
  a16=(a16/a6);
  a9=(a9+a16);
  a37=(a37*a13);
  a40=(a40*a2);
  a37=(a37-a40);
  a40=(a32*a3);
  a16=(a33*a10);
  a40=(a40-a16);
  a16=(a33*a40);
  a6=(a39*a10);
  a41=(a32*a1);
  a6=(a6-a41);
  a41=(a39*a6);
  a16=(a16-a41);
  a37=(a37-a16);
  a16=(a27*a1);
  a41=(a21*a3);
  a16=(a16-a41);
  a37=(a37-a16);
  a9=(a9+a37);
  a9=(a0*a9);
  if (res[0]!=0) res[0][33]=a9;
  a9=(a4*a3);
  a38=(a38*a12);
  a24=(a24*a13);
  a38=(a38-a24);
  a24=(a33*a1);
  a13=(a39*a3);
  a24=(a24-a13);
  a39=(a39*a24);
  a40=(a32*a40);
  a39=(a39-a40);
  a38=(a38-a39);
  a21=(a21*a10);
  a39=(a25*a1);
  a21=(a21-a39);
  a38=(a38-a21);
  a9=(a9+a38);
  a9=(a0*a9);
  if (res[0]!=0) res[0][34]=a9;
  a4=(a4*a1);
  a14=(a14*a2);
  a17=(a17*a12);
  a14=(a14-a17);
  a32=(a32*a6);
  a33=(a33*a24);
  a32=(a32-a33);
  a14=(a14-a32);
  a25=(a25*a3);
  a27=(a27*a10);
  a25=(a25-a27);
  a14=(a14-a25);
  a4=(a4+a14);
  a0=(a0*a4);
  if (res[0]!=0) res[0][35]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int fdrift(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int fdrift_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int fdrift_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fdrift_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int fdrift_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void fdrift_release(int mem) {
}

CASADI_SYMBOL_EXPORT void fdrift_incref(void) {
}

CASADI_SYMBOL_EXPORT void fdrift_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int fdrift_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int fdrift_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real fdrift_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fdrift_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* fdrift_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fdrift_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* fdrift_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s1;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int fdrift_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_fdrift(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[122];
  casadi_int *iw = 0;
  const casadi_real* arg[3] = {0};
  casadi_real* res[1] = {0};
  if (argc>3) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"fdrift\" failed. Too many input arguments (%d, max 3)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"fdrift\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+79);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+1, casadi_s1, w+79);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+37, casadi_s2, w+79);
  --resc;
  res[0] = w+43;
  i = fdrift(arg, res, iw, w+79, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"fdrift\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s1, res[0]);
}
#endif

casadi_int main_fdrift(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[122];
  const casadi_real* arg[3];
  casadi_real* res[1];
  arg[0] = w+0;
  arg[1] = w+1;
  arg[2] = w+37;
  res[0] = w+43;
  a = w;
  for (j=0; j<43; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = fdrift(arg, res, iw, w+79, 0);
  if (flag) return flag;
  r = w+43;
  for (j=0; j<36; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[7];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_fdrift(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "fdrift")==0) {
    mex_fdrift(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'fdrift'");
}
#endif
int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "fdrift")==0) {
    return main_fdrift(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'fdrift'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
