/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) dLdx_ ## ID
#endif

#include <math.h>
#include <stdio.h>
#include <string.h>
#ifdef MATLAB_MEX_FILE
#include <mex.h>
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_fill CASADI_PREFIX(fill)
#define casadi_from_mex CASADI_PREFIX(from_mex)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_to_mex CASADI_PREFIX(to_mex)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

void casadi_fill(casadi_real* x, casadi_int n, casadi_real alpha) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = alpha;
  }
}

#ifdef MATLAB_MEX_FILE
casadi_real* casadi_from_mex(const mxArray* p, casadi_real* y, const casadi_int* sp, casadi_real* w) {
  casadi_int nrow, ncol, is_sparse, c, k, p_nrow, p_ncol;
  const casadi_int *colind, *row;
  mwIndex *Jc, *Ir;
  const double* p_data;
  if (!mxIsDouble(p) || mxGetNumberOfDimensions(p)!=2)
    mexErrMsgIdAndTxt("Casadi:RuntimeError",
      "\"from_mex\" failed: Not a two-dimensional matrix of double precision.");
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
  p_nrow = mxGetM(p);
  p_ncol = mxGetN(p);
  is_sparse = mxIsSparse(p);
  Jc = 0;
  Ir = 0;
  if (is_sparse) {
    Jc = mxGetJc(p);
    Ir = mxGetIr(p);
  }
  p_data = (const double*)mxGetData(p);
  if (p_nrow==1 && p_ncol==1) {
    casadi_int nnz;
    double v = is_sparse && Jc[1]==0 ? 0 : *p_data;
    nnz = sp[ncol];
    casadi_fill(y, nnz, v);
  } else {
    casadi_int tr = 0;
    if (nrow!=p_nrow || ncol!=p_ncol) {
      tr = nrow==p_ncol && ncol==p_nrow && (nrow==1 || ncol==1);
      if (!tr) mexErrMsgIdAndTxt("Casadi:RuntimeError",
                                 "\"from_mex\" failed: Dimension mismatch. "
                                 "Expected %d-by-%d, got %d-by-%d instead.",
                                 nrow, ncol, p_nrow, p_ncol);
    }
    if (is_sparse) {
      if (tr) {
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]+c*nrow]=0;
        for (c=0; c<p_ncol; ++c)
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[c+Ir[k]*p_ncol] = p_data[k];
        for (c=0; c<ncol; ++c)
          for (k=colind[c]; k<colind[c+1]; ++k) y[k] = w[row[k]+c*nrow];
      } else {
        for (c=0; c<ncol; ++c) {
          for (k=colind[c]; k<colind[c+1]; ++k) w[row[k]]=0;
          for (k=Jc[c]; k<(casadi_int) Jc[c+1]; ++k) w[Ir[k]]=p_data[k];
          for (k=colind[c]; k<colind[c+1]; ++k) y[k]=w[row[k]];
        }
      }
    } else {
      for (c=0; c<ncol; ++c) {
        for (k=colind[c]; k<colind[c+1]; ++k) {
          y[k] = p_data[row[k]+c*nrow];
        }
      }
    }
  }
  return y;
}

#endif

#define casadi_to_double(x) ((double) x)

#ifdef MATLAB_MEX_FILE
mxArray* casadi_to_mex(const casadi_int* sp, const casadi_real* x) {
  casadi_int nrow, ncol, c, k;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int nnz;
#endif
  const casadi_int *colind, *row;
  mxArray *p;
  double *d;
#ifndef CASADI_MEX_NO_SPARSE
  casadi_int i;
  mwIndex *j;
#endif /* CASADI_MEX_NO_SPARSE */
  nrow = *sp++;
  ncol = *sp++;
  colind = sp;
  row = sp+ncol+1;
#ifndef CASADI_MEX_NO_SPARSE
  nnz = sp[ncol];
  if (nnz!=nrow*ncol) {
    p = mxCreateSparse(nrow, ncol, nnz, mxREAL);
    for (i=0, j=mxGetJc(p); i<=ncol; ++i) *j++ = *colind++;
    for (i=0, j=mxGetIr(p); i<nnz; ++i) *j++ = *row++;
    if (x) {
      d = (double*)mxGetData(p);
      for (i=0; i<nnz; ++i) *d++ = casadi_to_double(*x++);
    }
    return p;
  }
#endif /* CASADI_MEX_NO_SPARSE */
  p = mxCreateDoubleMatrix(nrow, ncol, mxREAL);
  if (x) {
    d = (double*)mxGetData(p);
    for (c=0; c<ncol; ++c) {
      for (k=colind[c]; k<colind[c+1]; ++k) {
        d[row[k]+c*nrow] = casadi_to_double(*x++);
      }
    }
  }
  return p;
}

#endif

#ifndef CASADI_PRINTF
#ifdef MATLAB_MEX_FILE
  #define CASADI_PRINTF mexPrintf
#else
  #define CASADI_PRINTF printf
#endif
#endif

static const casadi_int casadi_s0[16] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
static const casadi_int casadi_s1[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s2[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s3[4] = {1, 1, 0, 0};
static const casadi_int casadi_s4[58] = {1, 32, 0, 1, 1, 2, 3, 4, 5, 6, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 23, 23, 23, 23, 23, 23, 23, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* jac_L:(X[12],dX[12],k,t,XChief[6],out_CurveLength[1x1,0nz])->(jac[1x32,23nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a3, a4, a5, a6, a7, a8, a9;
  a0=7.0329494226657567e-03;
  a1=arg[1]? arg[1][3] : 0;
  a2=arg[0]? arg[0][0] : 0;
  a2=(a0*a2);
  a3=1.2566370614359172e+01;
  a4=arg[0]? arg[0][4] : 0;
  a5=(a3*a4);
  a2=(a2+a5);
  a1=(a1-a2);
  a1=(a1+a1);
  a2=(a0*a1);
  a2=(-a2);
  if (res[0]!=0) res[0][0]=a2;
  a2=-2.3443164742219190e-03;
  a5=arg[1]? arg[1][5] : 0;
  a6=arg[0]? arg[0][2] : 0;
  a6=(a2*a6);
  a5=(a5-a6);
  a5=(a5+a5);
  a6=(a2*a5);
  a6=(-a6);
  if (res[0]!=0) res[0][1]=a6;
  a6=-1.2566370614359172e+01;
  a7=arg[1]? arg[1][4] : 0;
  a8=arg[0]? arg[0][3] : 0;
  a9=(a6*a8);
  a7=(a7-a9);
  a7=(a7+a7);
  a9=(a6*a7);
  a10=1.6840054676261389e+04;
  a11=arg[1]? arg[1][0] : 0;
  a8=(a10*a8);
  a12=(a11-a8);
  a13=arg[2]? arg[2][0] : 0;
  a14=(a12*a13);
  a11=(a11-a8);
  a11=(a13*a11);
  a8=(a14+a11);
  a8=(a10*a8);
  a9=(a9+a8);
  a9=(-a9);
  if (res[0]!=0) res[0][2]=a9;
  a9=(a3*a1);
  a8=arg[1]? arg[1][1] : 0;
  a4=(a10*a4);
  a15=(a8-a4);
  a16=(a15*a13);
  a8=(a8-a4);
  a8=(a13*a8);
  a4=(a16+a8);
  a4=(a10*a4);
  a9=(a9+a4);
  a9=(-a9);
  if (res[0]!=0) res[0][3]=a9;
  a9=arg[1]? arg[1][2] : 0;
  a4=arg[0]? arg[0][5] : 0;
  a4=(a10*a4);
  a17=(a9-a4);
  a18=(a17*a13);
  a9=(a9-a4);
  a9=(a13*a9);
  a4=(a18+a9);
  a4=(a10*a4);
  a4=(-a4);
  if (res[0]!=0) res[0][4]=a4;
  a4=arg[1]? arg[1][9] : 0;
  a19=arg[0]? arg[0][6] : 0;
  a19=(a0*a19);
  a20=arg[0]? arg[0][10] : 0;
  a21=(a3*a20);
  a19=(a19+a21);
  a4=(a4-a19);
  a4=(a4+a4);
  a0=(a0*a4);
  a0=(-a0);
  if (res[0]!=0) res[0][5]=a0;
  a0=arg[1]? arg[1][11] : 0;
  a19=arg[0]? arg[0][8] : 0;
  a19=(a2*a19);
  a0=(a0-a19);
  a0=(a0+a0);
  a2=(a2*a0);
  a2=(-a2);
  if (res[0]!=0) res[0][6]=a2;
  a2=arg[1]? arg[1][10] : 0;
  a19=arg[0]? arg[0][9] : 0;
  a21=(a6*a19);
  a2=(a2-a21);
  a2=(a2+a2);
  a6=(a6*a2);
  a21=arg[1]? arg[1][6] : 0;
  a19=(a10*a19);
  a22=(a21-a19);
  a23=(a22*a13);
  a21=(a21-a19);
  a21=(a13*a21);
  a19=(a23+a21);
  a19=(a10*a19);
  a6=(a6+a19);
  a6=(-a6);
  if (res[0]!=0) res[0][7]=a6;
  a3=(a3*a4);
  a6=arg[1]? arg[1][7] : 0;
  a20=(a10*a20);
  a19=(a6-a20);
  a24=(a19*a13);
  a6=(a6-a20);
  a6=(a13*a6);
  a20=(a24+a6);
  a20=(a10*a20);
  a3=(a3+a20);
  a3=(-a3);
  if (res[0]!=0) res[0][8]=a3;
  a3=arg[1]? arg[1][8] : 0;
  a20=arg[0]? arg[0][11] : 0;
  a20=(a10*a20);
  a25=(a3-a20);
  a26=(a25*a13);
  a3=(a3-a20);
  a13=(a13*a3);
  a3=(a26+a13);
  a10=(a10*a3);
  a10=(-a10);
  if (res[0]!=0) res[0][9]=a10;
  a14=(a14+a11);
  if (res[0]!=0) res[0][10]=a14;
  a16=(a16+a8);
  if (res[0]!=0) res[0][11]=a16;
  a18=(a18+a9);
  if (res[0]!=0) res[0][12]=a18;
  if (res[0]!=0) res[0][13]=a1;
  if (res[0]!=0) res[0][14]=a7;
  if (res[0]!=0) res[0][15]=a5;
  a23=(a23+a21);
  if (res[0]!=0) res[0][16]=a23;
  a24=(a24+a6);
  if (res[0]!=0) res[0][17]=a24;
  a26=(a26+a13);
  if (res[0]!=0) res[0][18]=a26;
  if (res[0]!=0) res[0][19]=a4;
  if (res[0]!=0) res[0][20]=a2;
  if (res[0]!=0) res[0][21]=a0;
  a25=casadi_sq(a25);
  a19=casadi_sq(a19);
  a25=(a25+a19);
  a22=casadi_sq(a22);
  a25=(a25+a22);
  a17=casadi_sq(a17);
  a25=(a25+a17);
  a15=casadi_sq(a15);
  a25=(a25+a15);
  a12=casadi_sq(a12);
  a25=(a25+a12);
  if (res[0]!=0) res[0][22]=a25;
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_L(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int jac_L_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int jac_L_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_L_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int jac_L_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void jac_L_release(int mem) {
}

CASADI_SYMBOL_EXPORT void jac_L_incref(void) {
}

CASADI_SYMBOL_EXPORT void jac_L_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int jac_L_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int jac_L_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real jac_L_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_L_name_in(casadi_int i){
  switch (i) {
    case 0: return "X";
    case 1: return "dX";
    case 2: return "k";
    case 3: return "t";
    case 4: return "XChief";
    case 5: return "out_CurveLength";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* jac_L_name_out(casadi_int i){
  switch (i) {
    case 0: return "jac";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_L_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s1;
    case 4: return casadi_s2;
    case 5: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* jac_L_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int jac_L_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

#ifdef MATLAB_MEX_FILE
void mex_jac_L(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  casadi_int i;
  casadi_real w[82];
  casadi_int *iw = 0;
  const casadi_real* arg[6] = {0};
  casadi_real* res[1] = {0};
  if (argc>6) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"jac_L\" failed. Too many input arguments (%d, max 6)", argc);
  if (resc>1) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"jac_L\" failed. Too many output arguments (%d, max 1)", resc);
  if (--argc>=0) arg[0] = casadi_from_mex(argv[0], w, casadi_s0, w+55);
  if (--argc>=0) arg[1] = casadi_from_mex(argv[1], w+12, casadi_s0, w+55);
  if (--argc>=0) arg[2] = casadi_from_mex(argv[2], w+24, casadi_s1, w+55);
  if (--argc>=0) arg[3] = casadi_from_mex(argv[3], w+25, casadi_s1, w+55);
  if (--argc>=0) arg[4] = casadi_from_mex(argv[4], w+26, casadi_s2, w+55);
  if (--argc>=0) arg[5] = casadi_from_mex(argv[5], w+32, casadi_s3, w+55);
  --resc;
  res[0] = w+32;
  i = jac_L(arg, res, iw, w+55, 0);
  if (i) mexErrMsgIdAndTxt("Casadi:RuntimeError","Evaluation of \"jac_L\" failed.");
  if (res[0]) resv[0] = casadi_to_mex(casadi_s4, res[0]);
}
#endif

casadi_int main_jac_L(casadi_int argc, char* argv[]) {
  casadi_int j;
  casadi_real* a;
  const casadi_real* r;
  casadi_int flag;
  casadi_int *iw = 0;
  casadi_real w[82];
  const casadi_real* arg[6];
  casadi_real* res[1];
  arg[0] = w+0;
  arg[1] = w+12;
  arg[2] = w+24;
  arg[3] = w+25;
  arg[4] = w+26;
  arg[5] = w+32;
  res[0] = w+32;
  a = w;
  for (j=0; j<32; ++j) if (scanf("%lg", a++)<=0) return 2;
  flag = jac_L(arg, res, iw, w+55, 0);
  if (flag) return flag;
  r = w+32;
  for (j=0; j<23; ++j) CASADI_PRINTF("%g ", *r++);
  CASADI_PRINTF("\n");
  return 0;
}


#ifdef MATLAB_MEX_FILE
void mexFunction(int resc, mxArray *resv[], int argc, const mxArray *argv[]) {
  char buf[6];
  int buf_ok = argc > 0 && !mxGetString(*argv, buf, sizeof(buf));
  if (!buf_ok) {
    mex_jac_L(resc, resv, argc, argv);
    return;
  } else if (strcmp(buf, "jac_L")==0) {
    mex_jac_L(resc, resv, argc-1, argv+1);
    return;
  }
  mexErrMsgTxt("First input should be a command string. Possible values: 'jac_L'");
}
#endif
int main(int argc, char* argv[]) {
  if (argc<2) {
    /* name error */
  } else if (strcmp(argv[1], "jac_L")==0) {
    return main_jac_L(argc-2, argv+2);
  }
  fprintf(stderr, "First input should be a command string. Possible values: 'jac_L'\nNote: you may use function.generate_input to create a command string.\n");
  return 1;
}
#ifdef __cplusplus
} /* extern "C" */
#endif
